#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 13
#define STATE_COUNT 64
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 45
#define ALIAS_COUNT 0
#define TOKEN_COUNT 29
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 13
#define MAX_ALIAS_SEQUENCE_LENGTH 7
#define PRODUCTION_ID_COUNT 14

enum {
  sym_identifier = 1,
  sym_nil_literal = 2,
  sym_integer_literal = 3,
  anon_sym_DQUOTE = 4,
  aux_sym_string_literal_token1 = 5,
  sym_escape_sequence = 6,
  anon_sym_DOT = 7,
  anon_sym_LBRACK = 8,
  anon_sym_RBRACK = 9,
  anon_sym_LPAREN = 10,
  anon_sym_COMMA = 11,
  anon_sym_RPAREN = 12,
  anon_sym_DASH = 13,
  anon_sym_STAR = 14,
  anon_sym_SLASH = 15,
  anon_sym_PLUS = 16,
  anon_sym_GT_EQ = 17,
  anon_sym_LT_EQ = 18,
  anon_sym_EQ = 19,
  anon_sym_LT_GT = 20,
  anon_sym_LT = 21,
  anon_sym_GT = 22,
  anon_sym_AMP = 23,
  anon_sym_PIPE = 24,
  anon_sym_SEMI = 25,
  anon_sym_of = 26,
  anon_sym_LBRACE = 27,
  anon_sym_RBRACE = 28,
  sym_source_file = 29,
  sym__expr = 30,
  sym_string_literal = 31,
  sym__lvalue = 32,
  sym_record_value = 33,
  sym_array_value = 34,
  sym_function_call = 35,
  sym_unary_expression = 36,
  sym_binary_expression = 37,
  sym_sequence_expression = 38,
  sym_array_expression = 39,
  sym_record_expression = 40,
  aux_sym_string_literal_repeat1 = 41,
  aux_sym_function_call_repeat1 = 42,
  aux_sym_sequence_expression_repeat1 = 43,
  aux_sym_record_expression_repeat1 = 44,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [sym_nil_literal] = "nil_literal",
  [sym_integer_literal] = "integer_literal",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_string_literal_token1] = "string_literal_token1",
  [sym_escape_sequence] = "escape_sequence",
  [anon_sym_DOT] = ".",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_LPAREN] = "(",
  [anon_sym_COMMA] = ",",
  [anon_sym_RPAREN] = ")",
  [anon_sym_DASH] = "operator",
  [anon_sym_STAR] = "operator",
  [anon_sym_SLASH] = "operator",
  [anon_sym_PLUS] = "operator",
  [anon_sym_GT_EQ] = "operator",
  [anon_sym_LT_EQ] = "operator",
  [anon_sym_EQ] = "=",
  [anon_sym_LT_GT] = "operator",
  [anon_sym_LT] = "operator",
  [anon_sym_GT] = "operator",
  [anon_sym_AMP] = "operator",
  [anon_sym_PIPE] = "operator",
  [anon_sym_SEMI] = ";",
  [anon_sym_of] = "of",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [sym_source_file] = "source_file",
  [sym__expr] = "_expr",
  [sym_string_literal] = "string_literal",
  [sym__lvalue] = "_lvalue",
  [sym_record_value] = "record_value",
  [sym_array_value] = "array_value",
  [sym_function_call] = "function_call",
  [sym_unary_expression] = "unary_expression",
  [sym_binary_expression] = "binary_expression",
  [sym_sequence_expression] = "sequence_expression",
  [sym_array_expression] = "array_expression",
  [sym_record_expression] = "record_expression",
  [aux_sym_string_literal_repeat1] = "string_literal_repeat1",
  [aux_sym_function_call_repeat1] = "function_call_repeat1",
  [aux_sym_sequence_expression_repeat1] = "sequence_expression_repeat1",
  [aux_sym_record_expression_repeat1] = "record_expression_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [sym_nil_literal] = sym_nil_literal,
  [sym_integer_literal] = sym_integer_literal,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_string_literal_token1] = aux_sym_string_literal_token1,
  [sym_escape_sequence] = sym_escape_sequence,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_STAR] = anon_sym_DASH,
  [anon_sym_SLASH] = anon_sym_DASH,
  [anon_sym_PLUS] = anon_sym_DASH,
  [anon_sym_GT_EQ] = anon_sym_DASH,
  [anon_sym_LT_EQ] = anon_sym_DASH,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_LT_GT] = anon_sym_DASH,
  [anon_sym_LT] = anon_sym_DASH,
  [anon_sym_GT] = anon_sym_DASH,
  [anon_sym_AMP] = anon_sym_DASH,
  [anon_sym_PIPE] = anon_sym_DASH,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_of] = anon_sym_of,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [sym_source_file] = sym_source_file,
  [sym__expr] = sym__expr,
  [sym_string_literal] = sym_string_literal,
  [sym__lvalue] = sym__lvalue,
  [sym_record_value] = sym_record_value,
  [sym_array_value] = sym_array_value,
  [sym_function_call] = sym_function_call,
  [sym_unary_expression] = sym_unary_expression,
  [sym_binary_expression] = sym_binary_expression,
  [sym_sequence_expression] = sym_sequence_expression,
  [sym_array_expression] = sym_array_expression,
  [sym_record_expression] = sym_record_expression,
  [aux_sym_string_literal_repeat1] = aux_sym_string_literal_repeat1,
  [aux_sym_function_call_repeat1] = aux_sym_function_call_repeat1,
  [aux_sym_sequence_expression_repeat1] = aux_sym_sequence_expression_repeat1,
  [aux_sym_record_expression_repeat1] = aux_sym_record_expression_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_nil_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_integer_literal] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_literal_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_escape_sequence] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_GT_EQ] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LT_EQ] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_GT] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_AMP] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_of] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__expr] = {
    .visible = false,
    .named = true,
  },
  [sym_string_literal] = {
    .visible = true,
    .named = true,
  },
  [sym__lvalue] = {
    .visible = false,
    .named = true,
  },
  [sym_record_value] = {
    .visible = true,
    .named = true,
  },
  [sym_array_value] = {
    .visible = true,
    .named = true,
  },
  [sym_function_call] = {
    .visible = true,
    .named = true,
  },
  [sym_unary_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_binary_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_sequence_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_array_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_record_expression] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_string_literal_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_function_call_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_sequence_expression_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_record_expression_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum {
  field_arguments = 1,
  field_array = 2,
  field_expression = 3,
  field_field = 4,
  field_function = 5,
  field_index = 6,
  field_init = 7,
  field_left = 8,
  field_operator = 9,
  field_record = 10,
  field_right = 11,
  field_size = 12,
  field_type = 13,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_arguments] = "arguments",
  [field_array] = "array",
  [field_expression] = "expression",
  [field_field] = "field",
  [field_function] = "function",
  [field_index] = "index",
  [field_init] = "init",
  [field_left] = "left",
  [field_operator] = "operator",
  [field_record] = "record",
  [field_right] = "right",
  [field_size] = "size",
  [field_type] = "type",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
  [2] = {.index = 2, .length = 1},
  [3] = {.index = 3, .length = 1},
  [4] = {.index = 4, .length = 3},
  [5] = {.index = 7, .length = 2},
  [6] = {.index = 9, .length = 2},
  [7] = {.index = 11, .length = 2},
  [8] = {.index = 13, .length = 3},
  [9] = {.index = 16, .length = 3},
  [10] = {.index = 19, .length = 3},
  [11] = {.index = 22, .length = 5},
  [12] = {.index = 27, .length = 4},
  [13] = {.index = 31, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_expression, 1},
    {field_operator, 0},
  [2] =
    {field_function, 0},
  [3] =
    {field_type, 0},
  [4] =
    {field_left, 0},
    {field_operator, 1},
    {field_right, 2},
  [7] =
    {field_field, 2},
    {field_record, 0},
  [9] =
    {field_arguments, 2},
    {field_function, 0},
  [11] =
    {field_array, 0},
    {field_index, 2},
  [13] =
    {field_arguments, 2},
    {field_arguments, 3},
    {field_function, 0},
  [16] =
    {field_init, 5},
    {field_size, 2},
    {field_type, 0},
  [19] =
    {field_field, 2},
    {field_init, 4},
    {field_type, 0},
  [22] =
    {field_field, 2},
    {field_field, 5, .inherited = true},
    {field_init, 4},
    {field_init, 5, .inherited = true},
    {field_type, 0},
  [27] =
    {field_field, 0, .inherited = true},
    {field_field, 1, .inherited = true},
    {field_init, 0, .inherited = true},
    {field_init, 1, .inherited = true},
  [31] =
    {field_field, 1},
    {field_init, 3},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [4] = {
    [1] = anon_sym_DASH,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(9);
      if (lookahead == '"') ADVANCE(11);
      if (lookahead == '&') ADVANCE(32);
      if (lookahead == '(') ADVANCE(19);
      if (lookahead == ')') ADVANCE(21);
      if (lookahead == '*') ADVANCE(23);
      if (lookahead == '+') ADVANCE(25);
      if (lookahead == ',') ADVANCE(20);
      if (lookahead == '-') ADVANCE(22);
      if (lookahead == '.') ADVANCE(16);
      if (lookahead == '/') ADVANCE(24);
      if (lookahead == ';') ADVANCE(34);
      if (lookahead == '<') ADVANCE(30);
      if (lookahead == '=') ADVANCE(28);
      if (lookahead == '>') ADVANCE(31);
      if (lookahead == '[') ADVANCE(17);
      if (lookahead == '\\') ADVANCE(5);
      if (lookahead == ']') ADVANCE(18);
      if (lookahead == '{') ADVANCE(35);
      if (lookahead == '|') ADVANCE(33);
      if (lookahead == '}') ADVANCE(36);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(8)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(10);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(14);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(11);
      if (lookahead == '\\') ADVANCE(5);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(12);
      if (lookahead != 0) ADVANCE(13);
      END_STATE();
    case 2:
      if (lookahead == '}') ADVANCE(36);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(2)
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(14);
      END_STATE();
    case 3:
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(15);
      END_STATE();
    case 4:
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(3);
      END_STATE();
    case 5:
      if (lookahead == '"' ||
          lookahead == '\\' ||
          lookahead == 'a' ||
          lookahead == 'b' ||
          lookahead == 'f' ||
          lookahead == 'n' ||
          lookahead == 'r' ||
          lookahead == 't' ||
          lookahead == 'v') ADVANCE(15);
      if (lookahead == 'x') ADVANCE(7);
      if (('0' <= lookahead && lookahead <= '3')) ADVANCE(4);
      END_STATE();
    case 6:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(15);
      END_STATE();
    case 7:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(6);
      END_STATE();
    case 8:
      if (eof) ADVANCE(9);
      if (lookahead == '"') ADVANCE(11);
      if (lookahead == '&') ADVANCE(32);
      if (lookahead == '(') ADVANCE(19);
      if (lookahead == ')') ADVANCE(21);
      if (lookahead == '*') ADVANCE(23);
      if (lookahead == '+') ADVANCE(25);
      if (lookahead == ',') ADVANCE(20);
      if (lookahead == '-') ADVANCE(22);
      if (lookahead == '.') ADVANCE(16);
      if (lookahead == '/') ADVANCE(24);
      if (lookahead == ';') ADVANCE(34);
      if (lookahead == '<') ADVANCE(30);
      if (lookahead == '=') ADVANCE(28);
      if (lookahead == '>') ADVANCE(31);
      if (lookahead == '[') ADVANCE(17);
      if (lookahead == ']') ADVANCE(18);
      if (lookahead == '{') ADVANCE(35);
      if (lookahead == '|') ADVANCE(33);
      if (lookahead == '}') ADVANCE(36);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(8)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(10);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(14);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(sym_integer_literal);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(10);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(14);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(aux_sym_string_literal_token1);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(12);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(13);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(aux_sym_string_literal_token1);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(13);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(14);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_escape_sequence);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_GT_EQ);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_LT_EQ);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_LT_GT);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '=') ADVANCE(27);
      if (lookahead == '>') ADVANCE(29);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_GT);
      if (lookahead == '=') ADVANCE(26);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_AMP);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_PIPE);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'n') ADVANCE(1);
      if (lookahead == 'o') ADVANCE(2);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      END_STATE();
    case 1:
      if (lookahead == 'i') ADVANCE(3);
      END_STATE();
    case 2:
      if (lookahead == 'f') ADVANCE(4);
      END_STATE();
    case 3:
      if (lookahead == 'l') ADVANCE(5);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(anon_sym_of);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(sym_nil_literal);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 1},
  [49] = {.lex_state = 1},
  [50] = {.lex_state = 1},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 2},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 2},
  [60] = {.lex_state = 2},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 2},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [sym_nil_literal] = ACTIONS(1),
    [sym_integer_literal] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [sym_escape_sequence] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_GT_EQ] = ACTIONS(1),
    [anon_sym_LT_EQ] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_LT_GT] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_AMP] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_of] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(61),
    [sym__expr] = STATE(47),
    [sym_string_literal] = STATE(47),
    [sym__lvalue] = STATE(3),
    [sym_record_value] = STATE(3),
    [sym_array_value] = STATE(3),
    [sym_function_call] = STATE(47),
    [sym_unary_expression] = STATE(47),
    [sym_binary_expression] = STATE(47),
    [sym_sequence_expression] = STATE(47),
    [sym_array_expression] = STATE(47),
    [sym_record_expression] = STATE(47),
    [sym_identifier] = ACTIONS(3),
    [sym_nil_literal] = ACTIONS(5),
    [sym_integer_literal] = ACTIONS(5),
    [anon_sym_DQUOTE] = ACTIONS(7),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_DASH] = ACTIONS(11),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 5,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(18), 1,
      anon_sym_LPAREN,
    ACTIONS(22), 1,
      anon_sym_LBRACE,
    ACTIONS(20), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(13), 17,
      ts_builtin_sym_end,
      anon_sym_DOT,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PLUS,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [33] = 4,
    ACTIONS(26), 1,
      anon_sym_DOT,
    ACTIONS(28), 1,
      anon_sym_LBRACK,
    ACTIONS(30), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(24), 16,
      ts_builtin_sym_end,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PLUS,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [62] = 2,
    ACTIONS(34), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(32), 18,
      ts_builtin_sym_end,
      anon_sym_DOT,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PLUS,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [87] = 2,
    ACTIONS(38), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(36), 18,
      ts_builtin_sym_end,
      anon_sym_DOT,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PLUS,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [112] = 8,
    ACTIONS(3), 1,
      sym_identifier,
    ACTIONS(7), 1,
      anon_sym_DQUOTE,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_DASH,
    ACTIONS(42), 1,
      anon_sym_RPAREN,
    ACTIONS(40), 2,
      sym_nil_literal,
      sym_integer_literal,
    STATE(3), 3,
      sym__lvalue,
      sym_record_value,
      sym_array_value,
    STATE(40), 8,
      sym__expr,
      sym_string_literal,
      sym_function_call,
      sym_unary_expression,
      sym_binary_expression,
      sym_sequence_expression,
      sym_array_expression,
      sym_record_expression,
  [147] = 7,
    ACTIONS(54), 1,
      anon_sym_AMP,
    ACTIONS(56), 1,
      anon_sym_PIPE,
    ACTIONS(46), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(48), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(52), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(50), 4,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
    ACTIONS(44), 6,
      ts_builtin_sym_end,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [180] = 2,
    ACTIONS(60), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(58), 16,
      ts_builtin_sym_end,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PLUS,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [203] = 2,
    ACTIONS(64), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(62), 16,
      ts_builtin_sym_end,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PLUS,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [226] = 2,
    ACTIONS(68), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(66), 16,
      ts_builtin_sym_end,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PLUS,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [249] = 2,
    ACTIONS(72), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(70), 16,
      ts_builtin_sym_end,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PLUS,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [272] = 2,
    ACTIONS(76), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(74), 16,
      ts_builtin_sym_end,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PLUS,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [295] = 2,
    ACTIONS(80), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(78), 16,
      ts_builtin_sym_end,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PLUS,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [318] = 2,
    ACTIONS(84), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(82), 16,
      ts_builtin_sym_end,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PLUS,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [341] = 2,
    ACTIONS(88), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(86), 16,
      ts_builtin_sym_end,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PLUS,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [364] = 7,
    ACTIONS(54), 1,
      anon_sym_AMP,
    ACTIONS(56), 1,
      anon_sym_PIPE,
    ACTIONS(46), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(48), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(52), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(50), 4,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
    ACTIONS(90), 6,
      ts_builtin_sym_end,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [397] = 8,
    ACTIONS(3), 1,
      sym_identifier,
    ACTIONS(7), 1,
      anon_sym_DQUOTE,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_DASH,
    ACTIONS(94), 1,
      anon_sym_RPAREN,
    ACTIONS(92), 2,
      sym_nil_literal,
      sym_integer_literal,
    STATE(3), 3,
      sym__lvalue,
      sym_record_value,
      sym_array_value,
    STATE(39), 8,
      sym__expr,
      sym_string_literal,
      sym_function_call,
      sym_unary_expression,
      sym_binary_expression,
      sym_sequence_expression,
      sym_array_expression,
      sym_record_expression,
  [432] = 6,
    ACTIONS(54), 1,
      anon_sym_AMP,
    ACTIONS(46), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(48), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(52), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(50), 4,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
    ACTIONS(96), 7,
      ts_builtin_sym_end,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_PIPE,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [463] = 5,
    ACTIONS(46), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(48), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(52), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(50), 4,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
    ACTIONS(96), 8,
      ts_builtin_sym_end,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [492] = 4,
    ACTIONS(46), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(48), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(98), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(96), 12,
      ts_builtin_sym_end,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [519] = 2,
    ACTIONS(98), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(96), 16,
      ts_builtin_sym_end,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PLUS,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [542] = 3,
    ACTIONS(48), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(98), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(96), 14,
      ts_builtin_sym_end,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [567] = 2,
    ACTIONS(102), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(100), 16,
      ts_builtin_sym_end,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PLUS,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [590] = 2,
    ACTIONS(106), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(104), 16,
      ts_builtin_sym_end,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PLUS,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [613] = 2,
    ACTIONS(110), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(108), 16,
      ts_builtin_sym_end,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PLUS,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [636] = 7,
    ACTIONS(3), 1,
      sym_identifier,
    ACTIONS(7), 1,
      anon_sym_DQUOTE,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_DASH,
    ACTIONS(112), 2,
      sym_nil_literal,
      sym_integer_literal,
    STATE(3), 3,
      sym__lvalue,
      sym_record_value,
      sym_array_value,
    STATE(22), 8,
      sym__expr,
      sym_string_literal,
      sym_function_call,
      sym_unary_expression,
      sym_binary_expression,
      sym_sequence_expression,
      sym_array_expression,
      sym_record_expression,
  [668] = 7,
    ACTIONS(3), 1,
      sym_identifier,
    ACTIONS(7), 1,
      anon_sym_DQUOTE,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_DASH,
    ACTIONS(114), 2,
      sym_nil_literal,
      sym_integer_literal,
    STATE(3), 3,
      sym__lvalue,
      sym_record_value,
      sym_array_value,
    STATE(41), 8,
      sym__expr,
      sym_string_literal,
      sym_function_call,
      sym_unary_expression,
      sym_binary_expression,
      sym_sequence_expression,
      sym_array_expression,
      sym_record_expression,
  [700] = 7,
    ACTIONS(3), 1,
      sym_identifier,
    ACTIONS(7), 1,
      anon_sym_DQUOTE,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_DASH,
    ACTIONS(116), 2,
      sym_nil_literal,
      sym_integer_literal,
    STATE(3), 3,
      sym__lvalue,
      sym_record_value,
      sym_array_value,
    STATE(43), 8,
      sym__expr,
      sym_string_literal,
      sym_function_call,
      sym_unary_expression,
      sym_binary_expression,
      sym_sequence_expression,
      sym_array_expression,
      sym_record_expression,
  [732] = 7,
    ACTIONS(3), 1,
      sym_identifier,
    ACTIONS(7), 1,
      anon_sym_DQUOTE,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_DASH,
    ACTIONS(118), 2,
      sym_nil_literal,
      sym_integer_literal,
    STATE(3), 3,
      sym__lvalue,
      sym_record_value,
      sym_array_value,
    STATE(16), 8,
      sym__expr,
      sym_string_literal,
      sym_function_call,
      sym_unary_expression,
      sym_binary_expression,
      sym_sequence_expression,
      sym_array_expression,
      sym_record_expression,
  [764] = 7,
    ACTIONS(3), 1,
      sym_identifier,
    ACTIONS(7), 1,
      anon_sym_DQUOTE,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_DASH,
    ACTIONS(120), 2,
      sym_nil_literal,
      sym_integer_literal,
    STATE(3), 3,
      sym__lvalue,
      sym_record_value,
      sym_array_value,
    STATE(7), 8,
      sym__expr,
      sym_string_literal,
      sym_function_call,
      sym_unary_expression,
      sym_binary_expression,
      sym_sequence_expression,
      sym_array_expression,
      sym_record_expression,
  [796] = 7,
    ACTIONS(3), 1,
      sym_identifier,
    ACTIONS(7), 1,
      anon_sym_DQUOTE,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_DASH,
    ACTIONS(122), 2,
      sym_nil_literal,
      sym_integer_literal,
    STATE(3), 3,
      sym__lvalue,
      sym_record_value,
      sym_array_value,
    STATE(46), 8,
      sym__expr,
      sym_string_literal,
      sym_function_call,
      sym_unary_expression,
      sym_binary_expression,
      sym_sequence_expression,
      sym_array_expression,
      sym_record_expression,
  [828] = 7,
    ACTIONS(3), 1,
      sym_identifier,
    ACTIONS(7), 1,
      anon_sym_DQUOTE,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_DASH,
    ACTIONS(124), 2,
      sym_nil_literal,
      sym_integer_literal,
    STATE(3), 3,
      sym__lvalue,
      sym_record_value,
      sym_array_value,
    STATE(44), 8,
      sym__expr,
      sym_string_literal,
      sym_function_call,
      sym_unary_expression,
      sym_binary_expression,
      sym_sequence_expression,
      sym_array_expression,
      sym_record_expression,
  [860] = 7,
    ACTIONS(3), 1,
      sym_identifier,
    ACTIONS(7), 1,
      anon_sym_DQUOTE,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_DASH,
    ACTIONS(126), 2,
      sym_nil_literal,
      sym_integer_literal,
    STATE(3), 3,
      sym__lvalue,
      sym_record_value,
      sym_array_value,
    STATE(42), 8,
      sym__expr,
      sym_string_literal,
      sym_function_call,
      sym_unary_expression,
      sym_binary_expression,
      sym_sequence_expression,
      sym_array_expression,
      sym_record_expression,
  [892] = 7,
    ACTIONS(3), 1,
      sym_identifier,
    ACTIONS(7), 1,
      anon_sym_DQUOTE,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_DASH,
    ACTIONS(128), 2,
      sym_nil_literal,
      sym_integer_literal,
    STATE(3), 3,
      sym__lvalue,
      sym_record_value,
      sym_array_value,
    STATE(45), 8,
      sym__expr,
      sym_string_literal,
      sym_function_call,
      sym_unary_expression,
      sym_binary_expression,
      sym_sequence_expression,
      sym_array_expression,
      sym_record_expression,
  [924] = 7,
    ACTIONS(3), 1,
      sym_identifier,
    ACTIONS(7), 1,
      anon_sym_DQUOTE,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_DASH,
    ACTIONS(130), 2,
      sym_nil_literal,
      sym_integer_literal,
    STATE(3), 3,
      sym__lvalue,
      sym_record_value,
      sym_array_value,
    STATE(21), 8,
      sym__expr,
      sym_string_literal,
      sym_function_call,
      sym_unary_expression,
      sym_binary_expression,
      sym_sequence_expression,
      sym_array_expression,
      sym_record_expression,
  [956] = 7,
    ACTIONS(3), 1,
      sym_identifier,
    ACTIONS(7), 1,
      anon_sym_DQUOTE,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_DASH,
    ACTIONS(132), 2,
      sym_nil_literal,
      sym_integer_literal,
    STATE(3), 3,
      sym__lvalue,
      sym_record_value,
      sym_array_value,
    STATE(18), 8,
      sym__expr,
      sym_string_literal,
      sym_function_call,
      sym_unary_expression,
      sym_binary_expression,
      sym_sequence_expression,
      sym_array_expression,
      sym_record_expression,
  [988] = 7,
    ACTIONS(3), 1,
      sym_identifier,
    ACTIONS(7), 1,
      anon_sym_DQUOTE,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_DASH,
    ACTIONS(134), 2,
      sym_nil_literal,
      sym_integer_literal,
    STATE(3), 3,
      sym__lvalue,
      sym_record_value,
      sym_array_value,
    STATE(19), 8,
      sym__expr,
      sym_string_literal,
      sym_function_call,
      sym_unary_expression,
      sym_binary_expression,
      sym_sequence_expression,
      sym_array_expression,
      sym_record_expression,
  [1020] = 7,
    ACTIONS(3), 1,
      sym_identifier,
    ACTIONS(7), 1,
      anon_sym_DQUOTE,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_DASH,
    ACTIONS(136), 2,
      sym_nil_literal,
      sym_integer_literal,
    STATE(3), 3,
      sym__lvalue,
      sym_record_value,
      sym_array_value,
    STATE(20), 8,
      sym__expr,
      sym_string_literal,
      sym_function_call,
      sym_unary_expression,
      sym_binary_expression,
      sym_sequence_expression,
      sym_array_expression,
      sym_record_expression,
  [1052] = 9,
    ACTIONS(54), 1,
      anon_sym_AMP,
    ACTIONS(56), 1,
      anon_sym_PIPE,
    ACTIONS(138), 1,
      anon_sym_RPAREN,
    ACTIONS(140), 1,
      anon_sym_SEMI,
    STATE(56), 1,
      aux_sym_sequence_expression_repeat1,
    ACTIONS(46), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(48), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(52), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(50), 4,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
  [1086] = 9,
    ACTIONS(54), 1,
      anon_sym_AMP,
    ACTIONS(56), 1,
      anon_sym_PIPE,
    ACTIONS(142), 1,
      anon_sym_COMMA,
    ACTIONS(144), 1,
      anon_sym_RPAREN,
    STATE(55), 1,
      aux_sym_function_call_repeat1,
    ACTIONS(46), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(48), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(52), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(50), 4,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
  [1120] = 9,
    ACTIONS(54), 1,
      anon_sym_AMP,
    ACTIONS(56), 1,
      anon_sym_PIPE,
    ACTIONS(146), 1,
      anon_sym_COMMA,
    ACTIONS(148), 1,
      anon_sym_RBRACE,
    STATE(53), 1,
      aux_sym_record_expression_repeat1,
    ACTIONS(46), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(48), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(52), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(50), 4,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
  [1154] = 7,
    ACTIONS(54), 1,
      anon_sym_AMP,
    ACTIONS(56), 1,
      anon_sym_PIPE,
    ACTIONS(46), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(48), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(52), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(150), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
    ACTIONS(50), 4,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
  [1183] = 7,
    ACTIONS(54), 1,
      anon_sym_AMP,
    ACTIONS(56), 1,
      anon_sym_PIPE,
    ACTIONS(46), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(48), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(52), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(152), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
    ACTIONS(50), 4,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
  [1212] = 7,
    ACTIONS(54), 1,
      anon_sym_AMP,
    ACTIONS(56), 1,
      anon_sym_PIPE,
    ACTIONS(46), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(48), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(52), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(154), 2,
      anon_sym_RPAREN,
      anon_sym_SEMI,
    ACTIONS(50), 4,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
  [1241] = 7,
    ACTIONS(54), 1,
      anon_sym_AMP,
    ACTIONS(56), 1,
      anon_sym_PIPE,
    ACTIONS(156), 1,
      anon_sym_RBRACK,
    ACTIONS(46), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(48), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(52), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(50), 4,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
  [1269] = 7,
    ACTIONS(54), 1,
      anon_sym_AMP,
    ACTIONS(56), 1,
      anon_sym_PIPE,
    ACTIONS(158), 1,
      anon_sym_RBRACK,
    ACTIONS(46), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(48), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(52), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(50), 4,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
  [1297] = 7,
    ACTIONS(54), 1,
      anon_sym_AMP,
    ACTIONS(56), 1,
      anon_sym_PIPE,
    ACTIONS(160), 1,
      ts_builtin_sym_end,
    ACTIONS(46), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(48), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(52), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(50), 4,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
  [1325] = 3,
    ACTIONS(162), 1,
      anon_sym_DQUOTE,
    STATE(48), 1,
      aux_sym_string_literal_repeat1,
    ACTIONS(164), 2,
      aux_sym_string_literal_token1,
      sym_escape_sequence,
  [1336] = 3,
    ACTIONS(167), 1,
      anon_sym_DQUOTE,
    STATE(50), 1,
      aux_sym_string_literal_repeat1,
    ACTIONS(169), 2,
      aux_sym_string_literal_token1,
      sym_escape_sequence,
  [1347] = 3,
    ACTIONS(171), 1,
      anon_sym_DQUOTE,
    STATE(48), 1,
      aux_sym_string_literal_repeat1,
    ACTIONS(173), 2,
      aux_sym_string_literal_token1,
      sym_escape_sequence,
  [1358] = 3,
    ACTIONS(154), 1,
      anon_sym_RPAREN,
    ACTIONS(175), 1,
      anon_sym_SEMI,
    STATE(51), 1,
      aux_sym_sequence_expression_repeat1,
  [1368] = 3,
    ACTIONS(150), 1,
      anon_sym_RPAREN,
    ACTIONS(178), 1,
      anon_sym_COMMA,
    STATE(52), 1,
      aux_sym_function_call_repeat1,
  [1378] = 3,
    ACTIONS(146), 1,
      anon_sym_COMMA,
    ACTIONS(181), 1,
      anon_sym_RBRACE,
    STATE(54), 1,
      aux_sym_record_expression_repeat1,
  [1388] = 3,
    ACTIONS(183), 1,
      anon_sym_COMMA,
    ACTIONS(186), 1,
      anon_sym_RBRACE,
    STATE(54), 1,
      aux_sym_record_expression_repeat1,
  [1398] = 3,
    ACTIONS(142), 1,
      anon_sym_COMMA,
    ACTIONS(188), 1,
      anon_sym_RPAREN,
    STATE(52), 1,
      aux_sym_function_call_repeat1,
  [1408] = 3,
    ACTIONS(140), 1,
      anon_sym_SEMI,
    ACTIONS(190), 1,
      anon_sym_RPAREN,
    STATE(51), 1,
      aux_sym_sequence_expression_repeat1,
  [1418] = 2,
    ACTIONS(192), 1,
      sym_identifier,
    ACTIONS(194), 1,
      anon_sym_RBRACE,
  [1425] = 1,
    ACTIONS(196), 1,
      anon_sym_EQ,
  [1429] = 1,
    ACTIONS(198), 1,
      anon_sym_of,
  [1433] = 1,
    ACTIONS(200), 1,
      sym_identifier,
  [1437] = 1,
    ACTIONS(202), 1,
      ts_builtin_sym_end,
  [1441] = 1,
    ACTIONS(204), 1,
      anon_sym_EQ,
  [1445] = 1,
    ACTIONS(206), 1,
      sym_identifier,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 33,
  [SMALL_STATE(4)] = 62,
  [SMALL_STATE(5)] = 87,
  [SMALL_STATE(6)] = 112,
  [SMALL_STATE(7)] = 147,
  [SMALL_STATE(8)] = 180,
  [SMALL_STATE(9)] = 203,
  [SMALL_STATE(10)] = 226,
  [SMALL_STATE(11)] = 249,
  [SMALL_STATE(12)] = 272,
  [SMALL_STATE(13)] = 295,
  [SMALL_STATE(14)] = 318,
  [SMALL_STATE(15)] = 341,
  [SMALL_STATE(16)] = 364,
  [SMALL_STATE(17)] = 397,
  [SMALL_STATE(18)] = 432,
  [SMALL_STATE(19)] = 463,
  [SMALL_STATE(20)] = 492,
  [SMALL_STATE(21)] = 519,
  [SMALL_STATE(22)] = 542,
  [SMALL_STATE(23)] = 567,
  [SMALL_STATE(24)] = 590,
  [SMALL_STATE(25)] = 613,
  [SMALL_STATE(26)] = 636,
  [SMALL_STATE(27)] = 668,
  [SMALL_STATE(28)] = 700,
  [SMALL_STATE(29)] = 732,
  [SMALL_STATE(30)] = 764,
  [SMALL_STATE(31)] = 796,
  [SMALL_STATE(32)] = 828,
  [SMALL_STATE(33)] = 860,
  [SMALL_STATE(34)] = 892,
  [SMALL_STATE(35)] = 924,
  [SMALL_STATE(36)] = 956,
  [SMALL_STATE(37)] = 988,
  [SMALL_STATE(38)] = 1020,
  [SMALL_STATE(39)] = 1052,
  [SMALL_STATE(40)] = 1086,
  [SMALL_STATE(41)] = 1120,
  [SMALL_STATE(42)] = 1154,
  [SMALL_STATE(43)] = 1183,
  [SMALL_STATE(44)] = 1212,
  [SMALL_STATE(45)] = 1241,
  [SMALL_STATE(46)] = 1269,
  [SMALL_STATE(47)] = 1297,
  [SMALL_STATE(48)] = 1325,
  [SMALL_STATE(49)] = 1336,
  [SMALL_STATE(50)] = 1347,
  [SMALL_STATE(51)] = 1358,
  [SMALL_STATE(52)] = 1368,
  [SMALL_STATE(53)] = 1378,
  [SMALL_STATE(54)] = 1388,
  [SMALL_STATE(55)] = 1398,
  [SMALL_STATE(56)] = 1408,
  [SMALL_STATE(57)] = 1418,
  [SMALL_STATE(58)] = 1425,
  [SMALL_STATE(59)] = 1429,
  [SMALL_STATE(60)] = 1433,
  [SMALL_STATE(61)] = 1437,
  [SMALL_STATE(62)] = 1441,
  [SMALL_STATE(63)] = 1445,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(47),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__lvalue, 1),
  [15] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym__lvalue, 1), SHIFT(31),
  [18] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [20] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__lvalue, 1),
  [22] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [24] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expr, 1),
  [26] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [28] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [30] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__expr, 1),
  [32] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_record_value, 3, .production_id = 5),
  [34] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_record_value, 3, .production_id = 5),
  [36] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array_value, 4, .production_id = 7),
  [38] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array_value, 4, .production_id = 7),
  [40] = {.entry = {.count = 1, .reusable = false}}, SHIFT(40),
  [42] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [44] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array_expression, 6, .production_id = 9),
  [46] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [48] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [50] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [52] = {.entry = {.count = 1, .reusable = false}}, SHIFT(38),
  [54] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [56] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [58] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call, 5, .production_id = 8),
  [60] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_call, 5, .production_id = 8),
  [62] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string_literal, 2),
  [64] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string_literal, 2),
  [66] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_record_expression, 7, .production_id = 11),
  [68] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_record_expression, 7, .production_id = 11),
  [70] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sequence_expression, 4),
  [72] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_sequence_expression, 4),
  [74] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_record_expression, 3, .production_id = 3),
  [76] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_record_expression, 3, .production_id = 3),
  [78] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call, 4, .production_id = 6),
  [80] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_call, 4, .production_id = 6),
  [82] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sequence_expression, 2),
  [84] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_sequence_expression, 2),
  [86] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_record_expression, 6, .production_id = 10),
  [88] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_record_expression, 6, .production_id = 10),
  [90] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unary_expression, 2, .production_id = 1),
  [92] = {.entry = {.count = 1, .reusable = false}}, SHIFT(39),
  [94] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary_expression, 3, .production_id = 4),
  [98] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binary_expression, 3, .production_id = 4),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sequence_expression, 3),
  [102] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_sequence_expression, 3),
  [104] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string_literal, 3),
  [106] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string_literal, 3),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call, 3, .production_id = 2),
  [110] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_call, 3, .production_id = 2),
  [112] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [114] = {.entry = {.count = 1, .reusable = false}}, SHIFT(41),
  [116] = {.entry = {.count = 1, .reusable = false}}, SHIFT(43),
  [118] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [120] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [122] = {.entry = {.count = 1, .reusable = false}}, SHIFT(46),
  [124] = {.entry = {.count = 1, .reusable = false}}, SHIFT(44),
  [126] = {.entry = {.count = 1, .reusable = false}}, SHIFT(42),
  [128] = {.entry = {.count = 1, .reusable = false}}, SHIFT(45),
  [130] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [132] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [134] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [136] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [138] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [140] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [142] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [144] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [146] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [148] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [150] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_function_call_repeat1, 2),
  [152] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_record_expression_repeat1, 4, .production_id = 13),
  [154] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_sequence_expression_repeat1, 2),
  [156] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [158] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [160] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [162] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_literal_repeat1, 2),
  [164] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_literal_repeat1, 2), SHIFT_REPEAT(48),
  [167] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [169] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [171] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [173] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [175] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_sequence_expression_repeat1, 2), SHIFT_REPEAT(32),
  [178] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_function_call_repeat1, 2), SHIFT_REPEAT(33),
  [181] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [183] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_record_expression_repeat1, 2, .production_id = 12), SHIFT_REPEAT(60),
  [186] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_record_expression_repeat1, 2, .production_id = 12),
  [188] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [190] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [192] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [194] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [196] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [198] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [200] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [202] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [204] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [206] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_tiger(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
