#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 13
#define STATE_COUNT 84
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 58
#define ALIAS_COUNT 0
#define TOKEN_COUNT 38
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 19
#define MAX_ALIAS_SEQUENCE_LENGTH 8
#define PRODUCTION_ID_COUNT 19

enum {
  sym_identifier = 1,
  sym_nil_literal = 2,
  sym_integer_literal = 3,
  anon_sym_DQUOTE = 4,
  aux_sym_string_literal_token1 = 5,
  sym_escape_sequence = 6,
  anon_sym_DOT = 7,
  anon_sym_LBRACK = 8,
  anon_sym_RBRACK = 9,
  anon_sym_LPAREN = 10,
  anon_sym_COMMA = 11,
  anon_sym_RPAREN = 12,
  anon_sym_DASH = 13,
  anon_sym_STAR = 14,
  anon_sym_SLASH = 15,
  anon_sym_PLUS = 16,
  anon_sym_GT_EQ = 17,
  anon_sym_LT_EQ = 18,
  anon_sym_EQ = 19,
  anon_sym_LT_GT = 20,
  anon_sym_LT = 21,
  anon_sym_GT = 22,
  anon_sym_AMP = 23,
  anon_sym_PIPE = 24,
  anon_sym_SEMI = 25,
  anon_sym_of = 26,
  anon_sym_LBRACE = 27,
  anon_sym_RBRACE = 28,
  anon_sym_COLON_EQ = 29,
  anon_sym_if = 30,
  anon_sym_then = 31,
  anon_sym_else = 32,
  anon_sym_while = 33,
  anon_sym_do = 34,
  anon_sym_for = 35,
  anon_sym_to = 36,
  sym_break_expression = 37,
  sym_source_file = 38,
  sym__expr = 39,
  sym_string_literal = 40,
  sym__lvalue = 41,
  sym_record_value = 42,
  sym_array_value = 43,
  sym_function_call = 44,
  sym_unary_expression = 45,
  sym_binary_expression = 46,
  sym_sequence_expression = 47,
  sym_array_expression = 48,
  sym_record_expression = 49,
  sym_assignment_expression = 50,
  sym_if_expression = 51,
  sym_while_expression = 52,
  sym_for_expression = 53,
  aux_sym_string_literal_repeat1 = 54,
  aux_sym_function_call_repeat1 = 55,
  aux_sym_sequence_expression_repeat1 = 56,
  aux_sym_record_expression_repeat1 = 57,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [sym_nil_literal] = "nil_literal",
  [sym_integer_literal] = "integer_literal",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_string_literal_token1] = "string_literal_token1",
  [sym_escape_sequence] = "escape_sequence",
  [anon_sym_DOT] = ".",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_LPAREN] = "(",
  [anon_sym_COMMA] = ",",
  [anon_sym_RPAREN] = ")",
  [anon_sym_DASH] = "operator",
  [anon_sym_STAR] = "operator",
  [anon_sym_SLASH] = "operator",
  [anon_sym_PLUS] = "operator",
  [anon_sym_GT_EQ] = "operator",
  [anon_sym_LT_EQ] = "operator",
  [anon_sym_EQ] = "=",
  [anon_sym_LT_GT] = "operator",
  [anon_sym_LT] = "operator",
  [anon_sym_GT] = "operator",
  [anon_sym_AMP] = "operator",
  [anon_sym_PIPE] = "operator",
  [anon_sym_SEMI] = ";",
  [anon_sym_of] = "of",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_COLON_EQ] = ":=",
  [anon_sym_if] = "if",
  [anon_sym_then] = "then",
  [anon_sym_else] = "else",
  [anon_sym_while] = "while",
  [anon_sym_do] = "do",
  [anon_sym_for] = "for",
  [anon_sym_to] = "to",
  [sym_break_expression] = "break_expression",
  [sym_source_file] = "source_file",
  [sym__expr] = "_expr",
  [sym_string_literal] = "string_literal",
  [sym__lvalue] = "_lvalue",
  [sym_record_value] = "record_value",
  [sym_array_value] = "array_value",
  [sym_function_call] = "function_call",
  [sym_unary_expression] = "unary_expression",
  [sym_binary_expression] = "binary_expression",
  [sym_sequence_expression] = "sequence_expression",
  [sym_array_expression] = "array_expression",
  [sym_record_expression] = "record_expression",
  [sym_assignment_expression] = "assignment_expression",
  [sym_if_expression] = "if_expression",
  [sym_while_expression] = "while_expression",
  [sym_for_expression] = "for_expression",
  [aux_sym_string_literal_repeat1] = "string_literal_repeat1",
  [aux_sym_function_call_repeat1] = "function_call_repeat1",
  [aux_sym_sequence_expression_repeat1] = "sequence_expression_repeat1",
  [aux_sym_record_expression_repeat1] = "record_expression_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [sym_nil_literal] = sym_nil_literal,
  [sym_integer_literal] = sym_integer_literal,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_string_literal_token1] = aux_sym_string_literal_token1,
  [sym_escape_sequence] = sym_escape_sequence,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_STAR] = anon_sym_DASH,
  [anon_sym_SLASH] = anon_sym_DASH,
  [anon_sym_PLUS] = anon_sym_DASH,
  [anon_sym_GT_EQ] = anon_sym_DASH,
  [anon_sym_LT_EQ] = anon_sym_DASH,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_LT_GT] = anon_sym_DASH,
  [anon_sym_LT] = anon_sym_DASH,
  [anon_sym_GT] = anon_sym_DASH,
  [anon_sym_AMP] = anon_sym_DASH,
  [anon_sym_PIPE] = anon_sym_DASH,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_of] = anon_sym_of,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_COLON_EQ] = anon_sym_COLON_EQ,
  [anon_sym_if] = anon_sym_if,
  [anon_sym_then] = anon_sym_then,
  [anon_sym_else] = anon_sym_else,
  [anon_sym_while] = anon_sym_while,
  [anon_sym_do] = anon_sym_do,
  [anon_sym_for] = anon_sym_for,
  [anon_sym_to] = anon_sym_to,
  [sym_break_expression] = sym_break_expression,
  [sym_source_file] = sym_source_file,
  [sym__expr] = sym__expr,
  [sym_string_literal] = sym_string_literal,
  [sym__lvalue] = sym__lvalue,
  [sym_record_value] = sym_record_value,
  [sym_array_value] = sym_array_value,
  [sym_function_call] = sym_function_call,
  [sym_unary_expression] = sym_unary_expression,
  [sym_binary_expression] = sym_binary_expression,
  [sym_sequence_expression] = sym_sequence_expression,
  [sym_array_expression] = sym_array_expression,
  [sym_record_expression] = sym_record_expression,
  [sym_assignment_expression] = sym_assignment_expression,
  [sym_if_expression] = sym_if_expression,
  [sym_while_expression] = sym_while_expression,
  [sym_for_expression] = sym_for_expression,
  [aux_sym_string_literal_repeat1] = aux_sym_string_literal_repeat1,
  [aux_sym_function_call_repeat1] = aux_sym_function_call_repeat1,
  [aux_sym_sequence_expression_repeat1] = aux_sym_sequence_expression_repeat1,
  [aux_sym_record_expression_repeat1] = aux_sym_record_expression_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_nil_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_integer_literal] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_literal_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_escape_sequence] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_GT_EQ] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LT_EQ] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_GT] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_AMP] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_of] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_if] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_then] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_else] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_while] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_do] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_for] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_to] = {
    .visible = true,
    .named = false,
  },
  [sym_break_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__expr] = {
    .visible = false,
    .named = true,
  },
  [sym_string_literal] = {
    .visible = true,
    .named = true,
  },
  [sym__lvalue] = {
    .visible = false,
    .named = true,
  },
  [sym_record_value] = {
    .visible = true,
    .named = true,
  },
  [sym_array_value] = {
    .visible = true,
    .named = true,
  },
  [sym_function_call] = {
    .visible = true,
    .named = true,
  },
  [sym_unary_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_binary_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_sequence_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_array_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_record_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_assignment_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_if_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_while_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_for_expression] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_string_literal_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_function_call_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_sequence_expression_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_record_expression_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum {
  field_alternative = 1,
  field_arguments = 2,
  field_array = 3,
  field_body = 4,
  field_condition = 5,
  field_consequence = 6,
  field_end = 7,
  field_expression = 8,
  field_field = 9,
  field_function = 10,
  field_index = 11,
  field_init = 12,
  field_left = 13,
  field_operator = 14,
  field_record = 15,
  field_right = 16,
  field_size = 17,
  field_start = 18,
  field_type = 19,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_alternative] = "alternative",
  [field_arguments] = "arguments",
  [field_array] = "array",
  [field_body] = "body",
  [field_condition] = "condition",
  [field_consequence] = "consequence",
  [field_end] = "end",
  [field_expression] = "expression",
  [field_field] = "field",
  [field_function] = "function",
  [field_index] = "index",
  [field_init] = "init",
  [field_left] = "left",
  [field_operator] = "operator",
  [field_record] = "record",
  [field_right] = "right",
  [field_size] = "size",
  [field_start] = "start",
  [field_type] = "type",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
  [2] = {.index = 2, .length = 1},
  [3] = {.index = 3, .length = 1},
  [4] = {.index = 4, .length = 3},
  [5] = {.index = 7, .length = 2},
  [6] = {.index = 9, .length = 2},
  [7] = {.index = 11, .length = 2},
  [8] = {.index = 13, .length = 2},
  [9] = {.index = 15, .length = 2},
  [10] = {.index = 17, .length = 2},
  [11] = {.index = 19, .length = 3},
  [12] = {.index = 22, .length = 3},
  [13] = {.index = 25, .length = 3},
  [14] = {.index = 28, .length = 3},
  [15] = {.index = 31, .length = 5},
  [16] = {.index = 36, .length = 4},
  [17] = {.index = 40, .length = 4},
  [18] = {.index = 44, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_expression, 1},
    {field_operator, 0},
  [2] =
    {field_function, 0},
  [3] =
    {field_type, 0},
  [4] =
    {field_left, 0},
    {field_operator, 1},
    {field_right, 2},
  [7] =
    {field_field, 2},
    {field_record, 0},
  [9] =
    {field_left, 0},
    {field_right, 2},
  [11] =
    {field_arguments, 2},
    {field_function, 0},
  [13] =
    {field_condition, 1},
    {field_consequence, 3},
  [15] =
    {field_body, 3},
    {field_condition, 1},
  [17] =
    {field_array, 0},
    {field_index, 2},
  [19] =
    {field_arguments, 2},
    {field_arguments, 3},
    {field_function, 0},
  [22] =
    {field_init, 5},
    {field_size, 2},
    {field_type, 0},
  [25] =
    {field_field, 2},
    {field_init, 4},
    {field_type, 0},
  [28] =
    {field_alternative, 5},
    {field_condition, 1},
    {field_consequence, 3},
  [31] =
    {field_field, 2},
    {field_field, 5, .inherited = true},
    {field_init, 4},
    {field_init, 5, .inherited = true},
    {field_type, 0},
  [36] =
    {field_field, 0, .inherited = true},
    {field_field, 1, .inherited = true},
    {field_init, 0, .inherited = true},
    {field_init, 1, .inherited = true},
  [40] =
    {field_body, 7},
    {field_end, 5},
    {field_index, 1},
    {field_start, 3},
  [44] =
    {field_field, 1},
    {field_init, 3},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [4] = {
    [1] = anon_sym_DASH,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(10);
      if (lookahead == '"') ADVANCE(12);
      if (lookahead == '&') ADVANCE(33);
      if (lookahead == '(') ADVANCE(20);
      if (lookahead == ')') ADVANCE(22);
      if (lookahead == '*') ADVANCE(24);
      if (lookahead == '+') ADVANCE(26);
      if (lookahead == ',') ADVANCE(21);
      if (lookahead == '-') ADVANCE(23);
      if (lookahead == '.') ADVANCE(17);
      if (lookahead == '/') ADVANCE(25);
      if (lookahead == ':') ADVANCE(2);
      if (lookahead == ';') ADVANCE(35);
      if (lookahead == '<') ADVANCE(31);
      if (lookahead == '=') ADVANCE(29);
      if (lookahead == '>') ADVANCE(32);
      if (lookahead == '[') ADVANCE(18);
      if (lookahead == '\\') ADVANCE(5);
      if (lookahead == ']') ADVANCE(19);
      if (lookahead == '{') ADVANCE(36);
      if (lookahead == '|') ADVANCE(34);
      if (lookahead == '}') ADVANCE(37);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(8)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(11);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(15);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(12);
      if (lookahead == '\\') ADVANCE(5);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(13);
      if (lookahead != 0) ADVANCE(14);
      END_STATE();
    case 2:
      if (lookahead == '=') ADVANCE(38);
      END_STATE();
    case 3:
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(16);
      END_STATE();
    case 4:
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(3);
      END_STATE();
    case 5:
      if (lookahead == '"' ||
          lookahead == '\\' ||
          lookahead == 'a' ||
          lookahead == 'b' ||
          lookahead == 'f' ||
          lookahead == 'n' ||
          lookahead == 'r' ||
          lookahead == 't' ||
          lookahead == 'v') ADVANCE(16);
      if (lookahead == 'x') ADVANCE(7);
      if (('0' <= lookahead && lookahead <= '3')) ADVANCE(4);
      END_STATE();
    case 6:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(16);
      END_STATE();
    case 7:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(6);
      END_STATE();
    case 8:
      if (eof) ADVANCE(10);
      if (lookahead == '"') ADVANCE(12);
      if (lookahead == '&') ADVANCE(33);
      if (lookahead == '(') ADVANCE(20);
      if (lookahead == ')') ADVANCE(22);
      if (lookahead == '*') ADVANCE(24);
      if (lookahead == '+') ADVANCE(26);
      if (lookahead == ',') ADVANCE(21);
      if (lookahead == '-') ADVANCE(23);
      if (lookahead == '.') ADVANCE(17);
      if (lookahead == '/') ADVANCE(25);
      if (lookahead == ':') ADVANCE(2);
      if (lookahead == ';') ADVANCE(35);
      if (lookahead == '<') ADVANCE(31);
      if (lookahead == '=') ADVANCE(29);
      if (lookahead == '>') ADVANCE(32);
      if (lookahead == '[') ADVANCE(18);
      if (lookahead == ']') ADVANCE(19);
      if (lookahead == '{') ADVANCE(36);
      if (lookahead == '|') ADVANCE(34);
      if (lookahead == '}') ADVANCE(37);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(8)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(11);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(15);
      END_STATE();
    case 9:
      if (eof) ADVANCE(10);
      if (lookahead == '&') ADVANCE(33);
      if (lookahead == '(') ADVANCE(20);
      if (lookahead == ')') ADVANCE(22);
      if (lookahead == '*') ADVANCE(24);
      if (lookahead == '+') ADVANCE(26);
      if (lookahead == ',') ADVANCE(21);
      if (lookahead == '-') ADVANCE(23);
      if (lookahead == '.') ADVANCE(17);
      if (lookahead == '/') ADVANCE(25);
      if (lookahead == ':') ADVANCE(2);
      if (lookahead == ';') ADVANCE(35);
      if (lookahead == '<') ADVANCE(31);
      if (lookahead == '=') ADVANCE(29);
      if (lookahead == '>') ADVANCE(32);
      if (lookahead == '[') ADVANCE(18);
      if (lookahead == ']') ADVANCE(19);
      if (lookahead == '{') ADVANCE(36);
      if (lookahead == '|') ADVANCE(34);
      if (lookahead == '}') ADVANCE(37);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(9)
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(15);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(sym_integer_literal);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(11);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(15);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(aux_sym_string_literal_token1);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(13);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(14);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(aux_sym_string_literal_token1);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(14);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(15);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_escape_sequence);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_GT_EQ);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_LT_EQ);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_LT_GT);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '=') ADVANCE(28);
      if (lookahead == '>') ADVANCE(30);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_GT);
      if (lookahead == '=') ADVANCE(27);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_AMP);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_PIPE);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_COLON_EQ);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'b') ADVANCE(1);
      if (lookahead == 'd') ADVANCE(2);
      if (lookahead == 'e') ADVANCE(3);
      if (lookahead == 'f') ADVANCE(4);
      if (lookahead == 'i') ADVANCE(5);
      if (lookahead == 'n') ADVANCE(6);
      if (lookahead == 'o') ADVANCE(7);
      if (lookahead == 't') ADVANCE(8);
      if (lookahead == 'w') ADVANCE(9);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      END_STATE();
    case 1:
      if (lookahead == 'r') ADVANCE(10);
      END_STATE();
    case 2:
      if (lookahead == 'o') ADVANCE(11);
      END_STATE();
    case 3:
      if (lookahead == 'l') ADVANCE(12);
      END_STATE();
    case 4:
      if (lookahead == 'o') ADVANCE(13);
      END_STATE();
    case 5:
      if (lookahead == 'f') ADVANCE(14);
      END_STATE();
    case 6:
      if (lookahead == 'i') ADVANCE(15);
      END_STATE();
    case 7:
      if (lookahead == 'f') ADVANCE(16);
      END_STATE();
    case 8:
      if (lookahead == 'h') ADVANCE(17);
      if (lookahead == 'o') ADVANCE(18);
      END_STATE();
    case 9:
      if (lookahead == 'h') ADVANCE(19);
      END_STATE();
    case 10:
      if (lookahead == 'e') ADVANCE(20);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_do);
      END_STATE();
    case 12:
      if (lookahead == 's') ADVANCE(21);
      END_STATE();
    case 13:
      if (lookahead == 'r') ADVANCE(22);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_if);
      END_STATE();
    case 15:
      if (lookahead == 'l') ADVANCE(23);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_of);
      END_STATE();
    case 17:
      if (lookahead == 'e') ADVANCE(24);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_to);
      END_STATE();
    case 19:
      if (lookahead == 'i') ADVANCE(25);
      END_STATE();
    case 20:
      if (lookahead == 'a') ADVANCE(26);
      END_STATE();
    case 21:
      if (lookahead == 'e') ADVANCE(27);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_for);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_nil_literal);
      END_STATE();
    case 24:
      if (lookahead == 'n') ADVANCE(28);
      END_STATE();
    case 25:
      if (lookahead == 'l') ADVANCE(29);
      END_STATE();
    case 26:
      if (lookahead == 'k') ADVANCE(30);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_else);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_then);
      END_STATE();
    case 29:
      if (lookahead == 'e') ADVANCE(31);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_break_expression);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_while);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 9},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 9},
  [13] = {.lex_state = 9},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 9},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 9},
  [31] = {.lex_state = 9},
  [32] = {.lex_state = 9},
  [33] = {.lex_state = 9},
  [34] = {.lex_state = 9},
  [35] = {.lex_state = 9},
  [36] = {.lex_state = 9},
  [37] = {.lex_state = 9},
  [38] = {.lex_state = 9},
  [39] = {.lex_state = 9},
  [40] = {.lex_state = 9},
  [41] = {.lex_state = 9},
  [42] = {.lex_state = 9},
  [43] = {.lex_state = 9},
  [44] = {.lex_state = 9},
  [45] = {.lex_state = 9},
  [46] = {.lex_state = 9},
  [47] = {.lex_state = 9},
  [48] = {.lex_state = 9},
  [49] = {.lex_state = 9},
  [50] = {.lex_state = 9},
  [51] = {.lex_state = 9},
  [52] = {.lex_state = 9},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 9},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 9},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 9},
  [65] = {.lex_state = 9},
  [66] = {.lex_state = 1},
  [67] = {.lex_state = 1},
  [68] = {.lex_state = 1},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 9},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 9},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 9},
  [81] = {.lex_state = 9},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 9},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [sym_nil_literal] = ACTIONS(1),
    [sym_integer_literal] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [sym_escape_sequence] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_GT_EQ] = ACTIONS(1),
    [anon_sym_LT_EQ] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_LT_GT] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_AMP] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_of] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_COLON_EQ] = ACTIONS(1),
    [anon_sym_if] = ACTIONS(1),
    [anon_sym_then] = ACTIONS(1),
    [anon_sym_else] = ACTIONS(1),
    [anon_sym_while] = ACTIONS(1),
    [anon_sym_do] = ACTIONS(1),
    [anon_sym_for] = ACTIONS(1),
    [anon_sym_to] = ACTIONS(1),
    [sym_break_expression] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(82),
    [sym__expr] = STATE(60),
    [sym_string_literal] = STATE(60),
    [sym__lvalue] = STATE(12),
    [sym_record_value] = STATE(12),
    [sym_array_value] = STATE(12),
    [sym_function_call] = STATE(60),
    [sym_unary_expression] = STATE(60),
    [sym_binary_expression] = STATE(60),
    [sym_sequence_expression] = STATE(60),
    [sym_array_expression] = STATE(60),
    [sym_record_expression] = STATE(60),
    [sym_assignment_expression] = STATE(60),
    [sym_if_expression] = STATE(60),
    [sym_while_expression] = STATE(60),
    [sym_for_expression] = STATE(60),
    [sym_identifier] = ACTIONS(3),
    [sym_nil_literal] = ACTIONS(5),
    [sym_integer_literal] = ACTIONS(5),
    [anon_sym_DQUOTE] = ACTIONS(7),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_DASH] = ACTIONS(11),
    [anon_sym_if] = ACTIONS(13),
    [anon_sym_while] = ACTIONS(15),
    [anon_sym_for] = ACTIONS(17),
    [sym_break_expression] = ACTIONS(5),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 5,
    ACTIONS(21), 1,
      anon_sym_LBRACK,
    ACTIONS(24), 1,
      anon_sym_LPAREN,
    ACTIONS(28), 1,
      anon_sym_LBRACE,
    ACTIONS(26), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(19), 22,
      ts_builtin_sym_end,
      anon_sym_DOT,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PLUS,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_COLON_EQ,
      anon_sym_then,
      anon_sym_else,
      anon_sym_do,
      anon_sym_to,
  [38] = 11,
    ACTIONS(3), 1,
      sym_identifier,
    ACTIONS(7), 1,
      anon_sym_DQUOTE,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_DASH,
    ACTIONS(13), 1,
      anon_sym_if,
    ACTIONS(15), 1,
      anon_sym_while,
    ACTIONS(17), 1,
      anon_sym_for,
    ACTIONS(32), 1,
      anon_sym_RPAREN,
    ACTIONS(30), 3,
      sym_nil_literal,
      sym_integer_literal,
      sym_break_expression,
    STATE(12), 3,
      sym__lvalue,
      sym_record_value,
      sym_array_value,
    STATE(54), 12,
      sym__expr,
      sym_string_literal,
      sym_function_call,
      sym_unary_expression,
      sym_binary_expression,
      sym_sequence_expression,
      sym_array_expression,
      sym_record_expression,
      sym_assignment_expression,
      sym_if_expression,
      sym_while_expression,
      sym_for_expression,
  [87] = 11,
    ACTIONS(3), 1,
      sym_identifier,
    ACTIONS(7), 1,
      anon_sym_DQUOTE,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_DASH,
    ACTIONS(13), 1,
      anon_sym_if,
    ACTIONS(15), 1,
      anon_sym_while,
    ACTIONS(17), 1,
      anon_sym_for,
    ACTIONS(36), 1,
      anon_sym_RPAREN,
    ACTIONS(34), 3,
      sym_nil_literal,
      sym_integer_literal,
      sym_break_expression,
    STATE(12), 3,
      sym__lvalue,
      sym_record_value,
      sym_array_value,
    STATE(53), 12,
      sym__expr,
      sym_string_literal,
      sym_function_call,
      sym_unary_expression,
      sym_binary_expression,
      sym_sequence_expression,
      sym_array_expression,
      sym_record_expression,
      sym_assignment_expression,
      sym_if_expression,
      sym_while_expression,
      sym_for_expression,
  [136] = 10,
    ACTIONS(3), 1,
      sym_identifier,
    ACTIONS(7), 1,
      anon_sym_DQUOTE,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_DASH,
    ACTIONS(13), 1,
      anon_sym_if,
    ACTIONS(15), 1,
      anon_sym_while,
    ACTIONS(17), 1,
      anon_sym_for,
    ACTIONS(38), 3,
      sym_nil_literal,
      sym_integer_literal,
      sym_break_expression,
    STATE(12), 3,
      sym__lvalue,
      sym_record_value,
      sym_array_value,
    STATE(52), 12,
      sym__expr,
      sym_string_literal,
      sym_function_call,
      sym_unary_expression,
      sym_binary_expression,
      sym_sequence_expression,
      sym_array_expression,
      sym_record_expression,
      sym_assignment_expression,
      sym_if_expression,
      sym_while_expression,
      sym_for_expression,
  [182] = 10,
    ACTIONS(3), 1,
      sym_identifier,
    ACTIONS(7), 1,
      anon_sym_DQUOTE,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_DASH,
    ACTIONS(13), 1,
      anon_sym_if,
    ACTIONS(15), 1,
      anon_sym_while,
    ACTIONS(17), 1,
      anon_sym_for,
    ACTIONS(40), 3,
      sym_nil_literal,
      sym_integer_literal,
      sym_break_expression,
    STATE(12), 3,
      sym__lvalue,
      sym_record_value,
      sym_array_value,
    STATE(58), 12,
      sym__expr,
      sym_string_literal,
      sym_function_call,
      sym_unary_expression,
      sym_binary_expression,
      sym_sequence_expression,
      sym_array_expression,
      sym_record_expression,
      sym_assignment_expression,
      sym_if_expression,
      sym_while_expression,
      sym_for_expression,
  [228] = 10,
    ACTIONS(3), 1,
      sym_identifier,
    ACTIONS(7), 1,
      anon_sym_DQUOTE,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_DASH,
    ACTIONS(13), 1,
      anon_sym_if,
    ACTIONS(15), 1,
      anon_sym_while,
    ACTIONS(17), 1,
      anon_sym_for,
    ACTIONS(42), 3,
      sym_nil_literal,
      sym_integer_literal,
      sym_break_expression,
    STATE(12), 3,
      sym__lvalue,
      sym_record_value,
      sym_array_value,
    STATE(59), 12,
      sym__expr,
      sym_string_literal,
      sym_function_call,
      sym_unary_expression,
      sym_binary_expression,
      sym_sequence_expression,
      sym_array_expression,
      sym_record_expression,
      sym_assignment_expression,
      sym_if_expression,
      sym_while_expression,
      sym_for_expression,
  [274] = 10,
    ACTIONS(3), 1,
      sym_identifier,
    ACTIONS(7), 1,
      anon_sym_DQUOTE,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_DASH,
    ACTIONS(13), 1,
      anon_sym_if,
    ACTIONS(15), 1,
      anon_sym_while,
    ACTIONS(17), 1,
      anon_sym_for,
    ACTIONS(44), 3,
      sym_nil_literal,
      sym_integer_literal,
      sym_break_expression,
    STATE(12), 3,
      sym__lvalue,
      sym_record_value,
      sym_array_value,
    STATE(64), 12,
      sym__expr,
      sym_string_literal,
      sym_function_call,
      sym_unary_expression,
      sym_binary_expression,
      sym_sequence_expression,
      sym_array_expression,
      sym_record_expression,
      sym_assignment_expression,
      sym_if_expression,
      sym_while_expression,
      sym_for_expression,
  [320] = 10,
    ACTIONS(3), 1,
      sym_identifier,
    ACTIONS(7), 1,
      anon_sym_DQUOTE,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_DASH,
    ACTIONS(13), 1,
      anon_sym_if,
    ACTIONS(15), 1,
      anon_sym_while,
    ACTIONS(17), 1,
      anon_sym_for,
    ACTIONS(46), 3,
      sym_nil_literal,
      sym_integer_literal,
      sym_break_expression,
    STATE(12), 3,
      sym__lvalue,
      sym_record_value,
      sym_array_value,
    STATE(56), 12,
      sym__expr,
      sym_string_literal,
      sym_function_call,
      sym_unary_expression,
      sym_binary_expression,
      sym_sequence_expression,
      sym_array_expression,
      sym_record_expression,
      sym_assignment_expression,
      sym_if_expression,
      sym_while_expression,
      sym_for_expression,
  [366] = 10,
    ACTIONS(3), 1,
      sym_identifier,
    ACTIONS(7), 1,
      anon_sym_DQUOTE,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_DASH,
    ACTIONS(13), 1,
      anon_sym_if,
    ACTIONS(15), 1,
      anon_sym_while,
    ACTIONS(17), 1,
      anon_sym_for,
    ACTIONS(48), 3,
      sym_nil_literal,
      sym_integer_literal,
      sym_break_expression,
    STATE(12), 3,
      sym__lvalue,
      sym_record_value,
      sym_array_value,
    STATE(57), 12,
      sym__expr,
      sym_string_literal,
      sym_function_call,
      sym_unary_expression,
      sym_binary_expression,
      sym_sequence_expression,
      sym_array_expression,
      sym_record_expression,
      sym_assignment_expression,
      sym_if_expression,
      sym_while_expression,
      sym_for_expression,
  [412] = 10,
    ACTIONS(3), 1,
      sym_identifier,
    ACTIONS(7), 1,
      anon_sym_DQUOTE,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_DASH,
    ACTIONS(13), 1,
      anon_sym_if,
    ACTIONS(15), 1,
      anon_sym_while,
    ACTIONS(17), 1,
      anon_sym_for,
    ACTIONS(50), 3,
      sym_nil_literal,
      sym_integer_literal,
      sym_break_expression,
    STATE(12), 3,
      sym__lvalue,
      sym_record_value,
      sym_array_value,
    STATE(51), 12,
      sym__expr,
      sym_string_literal,
      sym_function_call,
      sym_unary_expression,
      sym_binary_expression,
      sym_sequence_expression,
      sym_array_expression,
      sym_record_expression,
      sym_assignment_expression,
      sym_if_expression,
      sym_while_expression,
      sym_for_expression,
  [458] = 5,
    ACTIONS(54), 1,
      anon_sym_DOT,
    ACTIONS(56), 1,
      anon_sym_LBRACK,
    ACTIONS(60), 1,
      anon_sym_COLON_EQ,
    ACTIONS(58), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(52), 20,
      ts_builtin_sym_end,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PLUS,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_then,
      anon_sym_else,
      anon_sym_do,
      anon_sym_to,
  [494] = 2,
    ACTIONS(64), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(62), 23,
      ts_builtin_sym_end,
      anon_sym_DOT,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PLUS,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_COLON_EQ,
      anon_sym_then,
      anon_sym_else,
      anon_sym_do,
      anon_sym_to,
  [524] = 10,
    ACTIONS(3), 1,
      sym_identifier,
    ACTIONS(7), 1,
      anon_sym_DQUOTE,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_DASH,
    ACTIONS(13), 1,
      anon_sym_if,
    ACTIONS(15), 1,
      anon_sym_while,
    ACTIONS(17), 1,
      anon_sym_for,
    ACTIONS(66), 3,
      sym_nil_literal,
      sym_integer_literal,
      sym_break_expression,
    STATE(12), 3,
      sym__lvalue,
      sym_record_value,
      sym_array_value,
    STATE(39), 12,
      sym__expr,
      sym_string_literal,
      sym_function_call,
      sym_unary_expression,
      sym_binary_expression,
      sym_sequence_expression,
      sym_array_expression,
      sym_record_expression,
      sym_assignment_expression,
      sym_if_expression,
      sym_while_expression,
      sym_for_expression,
  [570] = 10,
    ACTIONS(3), 1,
      sym_identifier,
    ACTIONS(7), 1,
      anon_sym_DQUOTE,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_DASH,
    ACTIONS(13), 1,
      anon_sym_if,
    ACTIONS(15), 1,
      anon_sym_while,
    ACTIONS(17), 1,
      anon_sym_for,
    ACTIONS(68), 3,
      sym_nil_literal,
      sym_integer_literal,
      sym_break_expression,
    STATE(12), 3,
      sym__lvalue,
      sym_record_value,
      sym_array_value,
    STATE(63), 12,
      sym__expr,
      sym_string_literal,
      sym_function_call,
      sym_unary_expression,
      sym_binary_expression,
      sym_sequence_expression,
      sym_array_expression,
      sym_record_expression,
      sym_assignment_expression,
      sym_if_expression,
      sym_while_expression,
      sym_for_expression,
  [616] = 2,
    ACTIONS(72), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(70), 23,
      ts_builtin_sym_end,
      anon_sym_DOT,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PLUS,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_COLON_EQ,
      anon_sym_then,
      anon_sym_else,
      anon_sym_do,
      anon_sym_to,
  [646] = 10,
    ACTIONS(3), 1,
      sym_identifier,
    ACTIONS(7), 1,
      anon_sym_DQUOTE,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_DASH,
    ACTIONS(13), 1,
      anon_sym_if,
    ACTIONS(15), 1,
      anon_sym_while,
    ACTIONS(17), 1,
      anon_sym_for,
    ACTIONS(74), 3,
      sym_nil_literal,
      sym_integer_literal,
      sym_break_expression,
    STATE(12), 3,
      sym__lvalue,
      sym_record_value,
      sym_array_value,
    STATE(36), 12,
      sym__expr,
      sym_string_literal,
      sym_function_call,
      sym_unary_expression,
      sym_binary_expression,
      sym_sequence_expression,
      sym_array_expression,
      sym_record_expression,
      sym_assignment_expression,
      sym_if_expression,
      sym_while_expression,
      sym_for_expression,
  [692] = 10,
    ACTIONS(3), 1,
      sym_identifier,
    ACTIONS(7), 1,
      anon_sym_DQUOTE,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_DASH,
    ACTIONS(13), 1,
      anon_sym_if,
    ACTIONS(15), 1,
      anon_sym_while,
    ACTIONS(17), 1,
      anon_sym_for,
    ACTIONS(76), 3,
      sym_nil_literal,
      sym_integer_literal,
      sym_break_expression,
    STATE(12), 3,
      sym__lvalue,
      sym_record_value,
      sym_array_value,
    STATE(30), 12,
      sym__expr,
      sym_string_literal,
      sym_function_call,
      sym_unary_expression,
      sym_binary_expression,
      sym_sequence_expression,
      sym_array_expression,
      sym_record_expression,
      sym_assignment_expression,
      sym_if_expression,
      sym_while_expression,
      sym_for_expression,
  [738] = 10,
    ACTIONS(3), 1,
      sym_identifier,
    ACTIONS(7), 1,
      anon_sym_DQUOTE,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_DASH,
    ACTIONS(13), 1,
      anon_sym_if,
    ACTIONS(15), 1,
      anon_sym_while,
    ACTIONS(17), 1,
      anon_sym_for,
    ACTIONS(78), 3,
      sym_nil_literal,
      sym_integer_literal,
      sym_break_expression,
    STATE(12), 3,
      sym__lvalue,
      sym_record_value,
      sym_array_value,
    STATE(55), 12,
      sym__expr,
      sym_string_literal,
      sym_function_call,
      sym_unary_expression,
      sym_binary_expression,
      sym_sequence_expression,
      sym_array_expression,
      sym_record_expression,
      sym_assignment_expression,
      sym_if_expression,
      sym_while_expression,
      sym_for_expression,
  [784] = 10,
    ACTIONS(3), 1,
      sym_identifier,
    ACTIONS(7), 1,
      anon_sym_DQUOTE,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_DASH,
    ACTIONS(13), 1,
      anon_sym_if,
    ACTIONS(15), 1,
      anon_sym_while,
    ACTIONS(17), 1,
      anon_sym_for,
    ACTIONS(80), 3,
      sym_nil_literal,
      sym_integer_literal,
      sym_break_expression,
    STATE(12), 3,
      sym__lvalue,
      sym_record_value,
      sym_array_value,
    STATE(44), 12,
      sym__expr,
      sym_string_literal,
      sym_function_call,
      sym_unary_expression,
      sym_binary_expression,
      sym_sequence_expression,
      sym_array_expression,
      sym_record_expression,
      sym_assignment_expression,
      sym_if_expression,
      sym_while_expression,
      sym_for_expression,
  [830] = 10,
    ACTIONS(3), 1,
      sym_identifier,
    ACTIONS(7), 1,
      anon_sym_DQUOTE,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_DASH,
    ACTIONS(13), 1,
      anon_sym_if,
    ACTIONS(15), 1,
      anon_sym_while,
    ACTIONS(17), 1,
      anon_sym_for,
    ACTIONS(82), 3,
      sym_nil_literal,
      sym_integer_literal,
      sym_break_expression,
    STATE(12), 3,
      sym__lvalue,
      sym_record_value,
      sym_array_value,
    STATE(61), 12,
      sym__expr,
      sym_string_literal,
      sym_function_call,
      sym_unary_expression,
      sym_binary_expression,
      sym_sequence_expression,
      sym_array_expression,
      sym_record_expression,
      sym_assignment_expression,
      sym_if_expression,
      sym_while_expression,
      sym_for_expression,
  [876] = 10,
    ACTIONS(3), 1,
      sym_identifier,
    ACTIONS(7), 1,
      anon_sym_DQUOTE,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_DASH,
    ACTIONS(13), 1,
      anon_sym_if,
    ACTIONS(15), 1,
      anon_sym_while,
    ACTIONS(17), 1,
      anon_sym_for,
    ACTIONS(84), 3,
      sym_nil_literal,
      sym_integer_literal,
      sym_break_expression,
    STATE(12), 3,
      sym__lvalue,
      sym_record_value,
      sym_array_value,
    STATE(50), 12,
      sym__expr,
      sym_string_literal,
      sym_function_call,
      sym_unary_expression,
      sym_binary_expression,
      sym_sequence_expression,
      sym_array_expression,
      sym_record_expression,
      sym_assignment_expression,
      sym_if_expression,
      sym_while_expression,
      sym_for_expression,
  [922] = 10,
    ACTIONS(3), 1,
      sym_identifier,
    ACTIONS(7), 1,
      anon_sym_DQUOTE,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_DASH,
    ACTIONS(13), 1,
      anon_sym_if,
    ACTIONS(15), 1,
      anon_sym_while,
    ACTIONS(17), 1,
      anon_sym_for,
    ACTIONS(86), 3,
      sym_nil_literal,
      sym_integer_literal,
      sym_break_expression,
    STATE(12), 3,
      sym__lvalue,
      sym_record_value,
      sym_array_value,
    STATE(35), 12,
      sym__expr,
      sym_string_literal,
      sym_function_call,
      sym_unary_expression,
      sym_binary_expression,
      sym_sequence_expression,
      sym_array_expression,
      sym_record_expression,
      sym_assignment_expression,
      sym_if_expression,
      sym_while_expression,
      sym_for_expression,
  [968] = 10,
    ACTIONS(3), 1,
      sym_identifier,
    ACTIONS(7), 1,
      anon_sym_DQUOTE,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_DASH,
    ACTIONS(13), 1,
      anon_sym_if,
    ACTIONS(15), 1,
      anon_sym_while,
    ACTIONS(17), 1,
      anon_sym_for,
    ACTIONS(88), 3,
      sym_nil_literal,
      sym_integer_literal,
      sym_break_expression,
    STATE(12), 3,
      sym__lvalue,
      sym_record_value,
      sym_array_value,
    STATE(47), 12,
      sym__expr,
      sym_string_literal,
      sym_function_call,
      sym_unary_expression,
      sym_binary_expression,
      sym_sequence_expression,
      sym_array_expression,
      sym_record_expression,
      sym_assignment_expression,
      sym_if_expression,
      sym_while_expression,
      sym_for_expression,
  [1014] = 10,
    ACTIONS(3), 1,
      sym_identifier,
    ACTIONS(7), 1,
      anon_sym_DQUOTE,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_DASH,
    ACTIONS(13), 1,
      anon_sym_if,
    ACTIONS(15), 1,
      anon_sym_while,
    ACTIONS(17), 1,
      anon_sym_for,
    ACTIONS(90), 3,
      sym_nil_literal,
      sym_integer_literal,
      sym_break_expression,
    STATE(12), 3,
      sym__lvalue,
      sym_record_value,
      sym_array_value,
    STATE(46), 12,
      sym__expr,
      sym_string_literal,
      sym_function_call,
      sym_unary_expression,
      sym_binary_expression,
      sym_sequence_expression,
      sym_array_expression,
      sym_record_expression,
      sym_assignment_expression,
      sym_if_expression,
      sym_while_expression,
      sym_for_expression,
  [1060] = 10,
    ACTIONS(3), 1,
      sym_identifier,
    ACTIONS(7), 1,
      anon_sym_DQUOTE,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_DASH,
    ACTIONS(13), 1,
      anon_sym_if,
    ACTIONS(15), 1,
      anon_sym_while,
    ACTIONS(17), 1,
      anon_sym_for,
    ACTIONS(92), 3,
      sym_nil_literal,
      sym_integer_literal,
      sym_break_expression,
    STATE(12), 3,
      sym__lvalue,
      sym_record_value,
      sym_array_value,
    STATE(31), 12,
      sym__expr,
      sym_string_literal,
      sym_function_call,
      sym_unary_expression,
      sym_binary_expression,
      sym_sequence_expression,
      sym_array_expression,
      sym_record_expression,
      sym_assignment_expression,
      sym_if_expression,
      sym_while_expression,
      sym_for_expression,
  [1106] = 10,
    ACTIONS(3), 1,
      sym_identifier,
    ACTIONS(7), 1,
      anon_sym_DQUOTE,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_DASH,
    ACTIONS(13), 1,
      anon_sym_if,
    ACTIONS(15), 1,
      anon_sym_while,
    ACTIONS(17), 1,
      anon_sym_for,
    ACTIONS(94), 3,
      sym_nil_literal,
      sym_integer_literal,
      sym_break_expression,
    STATE(12), 3,
      sym__lvalue,
      sym_record_value,
      sym_array_value,
    STATE(48), 12,
      sym__expr,
      sym_string_literal,
      sym_function_call,
      sym_unary_expression,
      sym_binary_expression,
      sym_sequence_expression,
      sym_array_expression,
      sym_record_expression,
      sym_assignment_expression,
      sym_if_expression,
      sym_while_expression,
      sym_for_expression,
  [1152] = 10,
    ACTIONS(3), 1,
      sym_identifier,
    ACTIONS(7), 1,
      anon_sym_DQUOTE,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_DASH,
    ACTIONS(13), 1,
      anon_sym_if,
    ACTIONS(15), 1,
      anon_sym_while,
    ACTIONS(17), 1,
      anon_sym_for,
    ACTIONS(96), 3,
      sym_nil_literal,
      sym_integer_literal,
      sym_break_expression,
    STATE(12), 3,
      sym__lvalue,
      sym_record_value,
      sym_array_value,
    STATE(65), 12,
      sym__expr,
      sym_string_literal,
      sym_function_call,
      sym_unary_expression,
      sym_binary_expression,
      sym_sequence_expression,
      sym_array_expression,
      sym_record_expression,
      sym_assignment_expression,
      sym_if_expression,
      sym_while_expression,
      sym_for_expression,
  [1198] = 10,
    ACTIONS(3), 1,
      sym_identifier,
    ACTIONS(7), 1,
      anon_sym_DQUOTE,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_DASH,
    ACTIONS(13), 1,
      anon_sym_if,
    ACTIONS(15), 1,
      anon_sym_while,
    ACTIONS(17), 1,
      anon_sym_for,
    ACTIONS(98), 3,
      sym_nil_literal,
      sym_integer_literal,
      sym_break_expression,
    STATE(12), 3,
      sym__lvalue,
      sym_record_value,
      sym_array_value,
    STATE(62), 12,
      sym__expr,
      sym_string_literal,
      sym_function_call,
      sym_unary_expression,
      sym_binary_expression,
      sym_sequence_expression,
      sym_array_expression,
      sym_record_expression,
      sym_assignment_expression,
      sym_if_expression,
      sym_while_expression,
      sym_for_expression,
  [1244] = 8,
    ACTIONS(110), 1,
      anon_sym_AMP,
    ACTIONS(112), 1,
      anon_sym_PIPE,
    ACTIONS(114), 1,
      anon_sym_else,
    ACTIONS(102), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(104), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(108), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(106), 4,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
    ACTIONS(100), 9,
      ts_builtin_sym_end,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_then,
      anon_sym_do,
      anon_sym_to,
  [1283] = 5,
    ACTIONS(102), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(104), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(108), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(106), 4,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
    ACTIONS(116), 12,
      ts_builtin_sym_end,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_then,
      anon_sym_else,
      anon_sym_do,
      anon_sym_to,
  [1316] = 2,
    ACTIONS(120), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(118), 20,
      ts_builtin_sym_end,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PLUS,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_then,
      anon_sym_else,
      anon_sym_do,
      anon_sym_to,
  [1343] = 2,
    ACTIONS(124), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(122), 20,
      ts_builtin_sym_end,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PLUS,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_then,
      anon_sym_else,
      anon_sym_do,
      anon_sym_to,
  [1370] = 2,
    ACTIONS(128), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(126), 20,
      ts_builtin_sym_end,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PLUS,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_then,
      anon_sym_else,
      anon_sym_do,
      anon_sym_to,
  [1397] = 3,
    ACTIONS(104), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(130), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(116), 18,
      ts_builtin_sym_end,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_then,
      anon_sym_else,
      anon_sym_do,
      anon_sym_to,
  [1426] = 7,
    ACTIONS(110), 1,
      anon_sym_AMP,
    ACTIONS(112), 1,
      anon_sym_PIPE,
    ACTIONS(102), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(104), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(108), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(106), 4,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
    ACTIONS(132), 10,
      ts_builtin_sym_end,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_then,
      anon_sym_else,
      anon_sym_do,
      anon_sym_to,
  [1463] = 2,
    ACTIONS(136), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(134), 20,
      ts_builtin_sym_end,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PLUS,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_then,
      anon_sym_else,
      anon_sym_do,
      anon_sym_to,
  [1490] = 2,
    ACTIONS(140), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(138), 20,
      ts_builtin_sym_end,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PLUS,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_then,
      anon_sym_else,
      anon_sym_do,
      anon_sym_to,
  [1517] = 7,
    ACTIONS(110), 1,
      anon_sym_AMP,
    ACTIONS(112), 1,
      anon_sym_PIPE,
    ACTIONS(102), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(104), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(108), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(106), 4,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
    ACTIONS(142), 10,
      ts_builtin_sym_end,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_then,
      anon_sym_else,
      anon_sym_do,
      anon_sym_to,
  [1554] = 2,
    ACTIONS(146), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(144), 20,
      ts_builtin_sym_end,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PLUS,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_then,
      anon_sym_else,
      anon_sym_do,
      anon_sym_to,
  [1581] = 2,
    ACTIONS(150), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(148), 20,
      ts_builtin_sym_end,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PLUS,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_then,
      anon_sym_else,
      anon_sym_do,
      anon_sym_to,
  [1608] = 2,
    ACTIONS(154), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(152), 20,
      ts_builtin_sym_end,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PLUS,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_then,
      anon_sym_else,
      anon_sym_do,
      anon_sym_to,
  [1635] = 2,
    ACTIONS(158), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(156), 20,
      ts_builtin_sym_end,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PLUS,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_then,
      anon_sym_else,
      anon_sym_do,
      anon_sym_to,
  [1662] = 7,
    ACTIONS(110), 1,
      anon_sym_AMP,
    ACTIONS(112), 1,
      anon_sym_PIPE,
    ACTIONS(102), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(104), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(108), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(106), 4,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
    ACTIONS(160), 10,
      ts_builtin_sym_end,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_then,
      anon_sym_else,
      anon_sym_do,
      anon_sym_to,
  [1699] = 2,
    ACTIONS(164), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(162), 20,
      ts_builtin_sym_end,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PLUS,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_then,
      anon_sym_else,
      anon_sym_do,
      anon_sym_to,
  [1726] = 4,
    ACTIONS(102), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(104), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(130), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(116), 16,
      ts_builtin_sym_end,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_then,
      anon_sym_else,
      anon_sym_do,
      anon_sym_to,
  [1757] = 2,
    ACTIONS(130), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(116), 20,
      ts_builtin_sym_end,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PLUS,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_then,
      anon_sym_else,
      anon_sym_do,
      anon_sym_to,
  [1784] = 6,
    ACTIONS(110), 1,
      anon_sym_AMP,
    ACTIONS(102), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(104), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(108), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(106), 4,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
    ACTIONS(116), 11,
      ts_builtin_sym_end,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_PIPE,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_then,
      anon_sym_else,
      anon_sym_do,
      anon_sym_to,
  [1819] = 2,
    ACTIONS(168), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(166), 20,
      ts_builtin_sym_end,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PLUS,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_then,
      anon_sym_else,
      anon_sym_do,
      anon_sym_to,
  [1846] = 2,
    ACTIONS(172), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(170), 20,
      ts_builtin_sym_end,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PLUS,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_then,
      anon_sym_else,
      anon_sym_do,
      anon_sym_to,
  [1873] = 7,
    ACTIONS(110), 1,
      anon_sym_AMP,
    ACTIONS(112), 1,
      anon_sym_PIPE,
    ACTIONS(102), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(104), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(108), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(106), 4,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
    ACTIONS(174), 10,
      ts_builtin_sym_end,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_then,
      anon_sym_else,
      anon_sym_do,
      anon_sym_to,
  [1910] = 7,
    ACTIONS(110), 1,
      anon_sym_AMP,
    ACTIONS(112), 1,
      anon_sym_PIPE,
    ACTIONS(102), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(104), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(108), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(106), 4,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
    ACTIONS(176), 10,
      ts_builtin_sym_end,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_then,
      anon_sym_else,
      anon_sym_do,
      anon_sym_to,
  [1947] = 9,
    ACTIONS(110), 1,
      anon_sym_AMP,
    ACTIONS(112), 1,
      anon_sym_PIPE,
    ACTIONS(178), 1,
      anon_sym_RPAREN,
    ACTIONS(180), 1,
      anon_sym_SEMI,
    STATE(72), 1,
      aux_sym_sequence_expression_repeat1,
    ACTIONS(102), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(104), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(108), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(106), 4,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
  [1981] = 9,
    ACTIONS(110), 1,
      anon_sym_AMP,
    ACTIONS(112), 1,
      anon_sym_PIPE,
    ACTIONS(182), 1,
      anon_sym_COMMA,
    ACTIONS(184), 1,
      anon_sym_RPAREN,
    STATE(70), 1,
      aux_sym_function_call_repeat1,
    ACTIONS(102), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(104), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(108), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(106), 4,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
  [2015] = 9,
    ACTIONS(110), 1,
      anon_sym_AMP,
    ACTIONS(112), 1,
      anon_sym_PIPE,
    ACTIONS(186), 1,
      anon_sym_COMMA,
    ACTIONS(188), 1,
      anon_sym_RBRACE,
    STATE(74), 1,
      aux_sym_record_expression_repeat1,
    ACTIONS(102), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(104), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(108), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(106), 4,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
  [2049] = 7,
    ACTIONS(110), 1,
      anon_sym_AMP,
    ACTIONS(112), 1,
      anon_sym_PIPE,
    ACTIONS(102), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(104), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(108), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(190), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
    ACTIONS(106), 4,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
  [2078] = 7,
    ACTIONS(110), 1,
      anon_sym_AMP,
    ACTIONS(112), 1,
      anon_sym_PIPE,
    ACTIONS(102), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(104), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(108), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(192), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
    ACTIONS(106), 4,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
  [2107] = 7,
    ACTIONS(110), 1,
      anon_sym_AMP,
    ACTIONS(112), 1,
      anon_sym_PIPE,
    ACTIONS(102), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(104), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(108), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(194), 2,
      anon_sym_RPAREN,
      anon_sym_SEMI,
    ACTIONS(106), 4,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
  [2136] = 7,
    ACTIONS(110), 1,
      anon_sym_AMP,
    ACTIONS(112), 1,
      anon_sym_PIPE,
    ACTIONS(196), 1,
      anon_sym_then,
    ACTIONS(102), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(104), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(108), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(106), 4,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
  [2164] = 7,
    ACTIONS(110), 1,
      anon_sym_AMP,
    ACTIONS(112), 1,
      anon_sym_PIPE,
    ACTIONS(198), 1,
      ts_builtin_sym_end,
    ACTIONS(102), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(104), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(108), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(106), 4,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
  [2192] = 7,
    ACTIONS(110), 1,
      anon_sym_AMP,
    ACTIONS(112), 1,
      anon_sym_PIPE,
    ACTIONS(200), 1,
      anon_sym_to,
    ACTIONS(102), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(104), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(108), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(106), 4,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
  [2220] = 7,
    ACTIONS(110), 1,
      anon_sym_AMP,
    ACTIONS(112), 1,
      anon_sym_PIPE,
    ACTIONS(202), 1,
      anon_sym_RBRACK,
    ACTIONS(102), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(104), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(108), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(106), 4,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
  [2248] = 7,
    ACTIONS(110), 1,
      anon_sym_AMP,
    ACTIONS(112), 1,
      anon_sym_PIPE,
    ACTIONS(204), 1,
      anon_sym_RBRACK,
    ACTIONS(102), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(104), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(108), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(106), 4,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
  [2276] = 7,
    ACTIONS(110), 1,
      anon_sym_AMP,
    ACTIONS(112), 1,
      anon_sym_PIPE,
    ACTIONS(206), 1,
      anon_sym_do,
    ACTIONS(102), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(104), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(108), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(106), 4,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
  [2304] = 7,
    ACTIONS(110), 1,
      anon_sym_AMP,
    ACTIONS(112), 1,
      anon_sym_PIPE,
    ACTIONS(208), 1,
      anon_sym_do,
    ACTIONS(102), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(104), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(108), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(106), 4,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
  [2332] = 3,
    ACTIONS(210), 1,
      anon_sym_DQUOTE,
    STATE(68), 1,
      aux_sym_string_literal_repeat1,
    ACTIONS(212), 2,
      aux_sym_string_literal_token1,
      sym_escape_sequence,
  [2343] = 3,
    ACTIONS(214), 1,
      anon_sym_DQUOTE,
    STATE(67), 1,
      aux_sym_string_literal_repeat1,
    ACTIONS(216), 2,
      aux_sym_string_literal_token1,
      sym_escape_sequence,
  [2354] = 3,
    ACTIONS(219), 1,
      anon_sym_DQUOTE,
    STATE(67), 1,
      aux_sym_string_literal_repeat1,
    ACTIONS(221), 2,
      aux_sym_string_literal_token1,
      sym_escape_sequence,
  [2365] = 3,
    ACTIONS(223), 1,
      anon_sym_COMMA,
    ACTIONS(226), 1,
      anon_sym_RBRACE,
    STATE(69), 1,
      aux_sym_record_expression_repeat1,
  [2375] = 3,
    ACTIONS(182), 1,
      anon_sym_COMMA,
    ACTIONS(228), 1,
      anon_sym_RPAREN,
    STATE(73), 1,
      aux_sym_function_call_repeat1,
  [2385] = 3,
    ACTIONS(194), 1,
      anon_sym_RPAREN,
    ACTIONS(230), 1,
      anon_sym_SEMI,
    STATE(71), 1,
      aux_sym_sequence_expression_repeat1,
  [2395] = 3,
    ACTIONS(180), 1,
      anon_sym_SEMI,
    ACTIONS(233), 1,
      anon_sym_RPAREN,
    STATE(71), 1,
      aux_sym_sequence_expression_repeat1,
  [2405] = 3,
    ACTIONS(190), 1,
      anon_sym_RPAREN,
    ACTIONS(235), 1,
      anon_sym_COMMA,
    STATE(73), 1,
      aux_sym_function_call_repeat1,
  [2415] = 3,
    ACTIONS(186), 1,
      anon_sym_COMMA,
    ACTIONS(238), 1,
      anon_sym_RBRACE,
    STATE(69), 1,
      aux_sym_record_expression_repeat1,
  [2425] = 2,
    ACTIONS(240), 1,
      sym_identifier,
    ACTIONS(242), 1,
      anon_sym_RBRACE,
  [2432] = 1,
    ACTIONS(244), 1,
      anon_sym_EQ,
  [2436] = 1,
    ACTIONS(246), 1,
      anon_sym_EQ,
  [2440] = 1,
    ACTIONS(248), 1,
      anon_sym_of,
  [2444] = 1,
    ACTIONS(250), 1,
      anon_sym_COLON_EQ,
  [2448] = 1,
    ACTIONS(252), 1,
      sym_identifier,
  [2452] = 1,
    ACTIONS(254), 1,
      sym_identifier,
  [2456] = 1,
    ACTIONS(256), 1,
      ts_builtin_sym_end,
  [2460] = 1,
    ACTIONS(258), 1,
      sym_identifier,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 38,
  [SMALL_STATE(4)] = 87,
  [SMALL_STATE(5)] = 136,
  [SMALL_STATE(6)] = 182,
  [SMALL_STATE(7)] = 228,
  [SMALL_STATE(8)] = 274,
  [SMALL_STATE(9)] = 320,
  [SMALL_STATE(10)] = 366,
  [SMALL_STATE(11)] = 412,
  [SMALL_STATE(12)] = 458,
  [SMALL_STATE(13)] = 494,
  [SMALL_STATE(14)] = 524,
  [SMALL_STATE(15)] = 570,
  [SMALL_STATE(16)] = 616,
  [SMALL_STATE(17)] = 646,
  [SMALL_STATE(18)] = 692,
  [SMALL_STATE(19)] = 738,
  [SMALL_STATE(20)] = 784,
  [SMALL_STATE(21)] = 830,
  [SMALL_STATE(22)] = 876,
  [SMALL_STATE(23)] = 922,
  [SMALL_STATE(24)] = 968,
  [SMALL_STATE(25)] = 1014,
  [SMALL_STATE(26)] = 1060,
  [SMALL_STATE(27)] = 1106,
  [SMALL_STATE(28)] = 1152,
  [SMALL_STATE(29)] = 1198,
  [SMALL_STATE(30)] = 1244,
  [SMALL_STATE(31)] = 1283,
  [SMALL_STATE(32)] = 1316,
  [SMALL_STATE(33)] = 1343,
  [SMALL_STATE(34)] = 1370,
  [SMALL_STATE(35)] = 1397,
  [SMALL_STATE(36)] = 1426,
  [SMALL_STATE(37)] = 1463,
  [SMALL_STATE(38)] = 1490,
  [SMALL_STATE(39)] = 1517,
  [SMALL_STATE(40)] = 1554,
  [SMALL_STATE(41)] = 1581,
  [SMALL_STATE(42)] = 1608,
  [SMALL_STATE(43)] = 1635,
  [SMALL_STATE(44)] = 1662,
  [SMALL_STATE(45)] = 1699,
  [SMALL_STATE(46)] = 1726,
  [SMALL_STATE(47)] = 1757,
  [SMALL_STATE(48)] = 1784,
  [SMALL_STATE(49)] = 1819,
  [SMALL_STATE(50)] = 1846,
  [SMALL_STATE(51)] = 1873,
  [SMALL_STATE(52)] = 1910,
  [SMALL_STATE(53)] = 1947,
  [SMALL_STATE(54)] = 1981,
  [SMALL_STATE(55)] = 2015,
  [SMALL_STATE(56)] = 2049,
  [SMALL_STATE(57)] = 2078,
  [SMALL_STATE(58)] = 2107,
  [SMALL_STATE(59)] = 2136,
  [SMALL_STATE(60)] = 2164,
  [SMALL_STATE(61)] = 2192,
  [SMALL_STATE(62)] = 2220,
  [SMALL_STATE(63)] = 2248,
  [SMALL_STATE(64)] = 2276,
  [SMALL_STATE(65)] = 2304,
  [SMALL_STATE(66)] = 2332,
  [SMALL_STATE(67)] = 2343,
  [SMALL_STATE(68)] = 2354,
  [SMALL_STATE(69)] = 2365,
  [SMALL_STATE(70)] = 2375,
  [SMALL_STATE(71)] = 2385,
  [SMALL_STATE(72)] = 2395,
  [SMALL_STATE(73)] = 2405,
  [SMALL_STATE(74)] = 2415,
  [SMALL_STATE(75)] = 2425,
  [SMALL_STATE(76)] = 2432,
  [SMALL_STATE(77)] = 2436,
  [SMALL_STATE(78)] = 2440,
  [SMALL_STATE(79)] = 2444,
  [SMALL_STATE(80)] = 2448,
  [SMALL_STATE(81)] = 2452,
  [SMALL_STATE(82)] = 2456,
  [SMALL_STATE(83)] = 2460,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(60),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(80),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__lvalue, 1),
  [21] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym__lvalue, 1), SHIFT(15),
  [24] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [26] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__lvalue, 1),
  [28] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [30] = {.entry = {.count = 1, .reusable = false}}, SHIFT(54),
  [32] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [34] = {.entry = {.count = 1, .reusable = false}}, SHIFT(53),
  [36] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [38] = {.entry = {.count = 1, .reusable = false}}, SHIFT(52),
  [40] = {.entry = {.count = 1, .reusable = false}}, SHIFT(58),
  [42] = {.entry = {.count = 1, .reusable = false}}, SHIFT(59),
  [44] = {.entry = {.count = 1, .reusable = false}}, SHIFT(64),
  [46] = {.entry = {.count = 1, .reusable = false}}, SHIFT(56),
  [48] = {.entry = {.count = 1, .reusable = false}}, SHIFT(57),
  [50] = {.entry = {.count = 1, .reusable = false}}, SHIFT(51),
  [52] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expr, 1),
  [54] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [56] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [58] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__expr, 1),
  [60] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [62] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_record_value, 3, .production_id = 5),
  [64] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_record_value, 3, .production_id = 5),
  [66] = {.entry = {.count = 1, .reusable = false}}, SHIFT(39),
  [68] = {.entry = {.count = 1, .reusable = false}}, SHIFT(63),
  [70] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array_value, 4, .production_id = 10),
  [72] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array_value, 4, .production_id = 10),
  [74] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [76] = {.entry = {.count = 1, .reusable = false}}, SHIFT(30),
  [78] = {.entry = {.count = 1, .reusable = false}}, SHIFT(55),
  [80] = {.entry = {.count = 1, .reusable = false}}, SHIFT(44),
  [82] = {.entry = {.count = 1, .reusable = false}}, SHIFT(61),
  [84] = {.entry = {.count = 1, .reusable = false}}, SHIFT(50),
  [86] = {.entry = {.count = 1, .reusable = false}}, SHIFT(35),
  [88] = {.entry = {.count = 1, .reusable = false}}, SHIFT(47),
  [90] = {.entry = {.count = 1, .reusable = false}}, SHIFT(46),
  [92] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [94] = {.entry = {.count = 1, .reusable = false}}, SHIFT(48),
  [96] = {.entry = {.count = 1, .reusable = false}}, SHIFT(65),
  [98] = {.entry = {.count = 1, .reusable = false}}, SHIFT(62),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_expression, 4, .production_id = 8),
  [102] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [104] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [106] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [108] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [110] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [112] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [114] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [116] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary_expression, 3, .production_id = 4),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_record_expression, 6, .production_id = 13),
  [120] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_record_expression, 6, .production_id = 13),
  [122] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call, 5, .production_id = 11),
  [124] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_call, 5, .production_id = 11),
  [126] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call, 3, .production_id = 2),
  [128] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_call, 3, .production_id = 2),
  [130] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binary_expression, 3, .production_id = 4),
  [132] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_while_expression, 4, .production_id = 9),
  [134] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_record_expression, 3, .production_id = 3),
  [136] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_record_expression, 3, .production_id = 3),
  [138] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sequence_expression, 3),
  [140] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_sequence_expression, 3),
  [142] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unary_expression, 2, .production_id = 1),
  [144] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call, 4, .production_id = 7),
  [146] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_call, 4, .production_id = 7),
  [148] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sequence_expression, 2),
  [150] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_sequence_expression, 2),
  [152] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string_literal, 3),
  [154] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string_literal, 3),
  [156] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sequence_expression, 4),
  [158] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_sequence_expression, 4),
  [160] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_expression, 6, .production_id = 14),
  [162] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_record_expression, 7, .production_id = 15),
  [164] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_record_expression, 7, .production_id = 15),
  [166] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string_literal, 2),
  [168] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string_literal, 2),
  [170] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assignment_expression, 3, .production_id = 6),
  [172] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_assignment_expression, 3, .production_id = 6),
  [174] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_for_expression, 8, .production_id = 17),
  [176] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array_expression, 6, .production_id = 12),
  [178] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [180] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [182] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [184] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [186] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [188] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [190] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_function_call_repeat1, 2),
  [192] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_record_expression_repeat1, 4, .production_id = 18),
  [194] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_sequence_expression_repeat1, 2),
  [196] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [198] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [200] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [202] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [204] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [206] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [208] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [210] = {.entry = {.count = 1, .reusable = false}}, SHIFT(49),
  [212] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [214] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_literal_repeat1, 2),
  [216] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_literal_repeat1, 2), SHIFT_REPEAT(67),
  [219] = {.entry = {.count = 1, .reusable = false}}, SHIFT(42),
  [221] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [223] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_record_expression_repeat1, 2, .production_id = 16), SHIFT_REPEAT(83),
  [226] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_record_expression_repeat1, 2, .production_id = 16),
  [228] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [230] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_sequence_expression_repeat1, 2), SHIFT_REPEAT(6),
  [233] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [235] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_function_call_repeat1, 2), SHIFT_REPEAT(9),
  [238] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [240] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [242] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [244] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [246] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [248] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [250] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [252] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [254] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [256] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [258] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_tiger(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
