#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 13
#define STATE_COUNT 66
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 47
#define ALIAS_COUNT 0
#define TOKEN_COUNT 30
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 13
#define MAX_ALIAS_SEQUENCE_LENGTH 7
#define PRODUCTION_ID_COUNT 15

enum {
  sym_identifier = 1,
  sym_nil_literal = 2,
  sym_integer_literal = 3,
  anon_sym_DQUOTE = 4,
  aux_sym_string_literal_token1 = 5,
  sym_escape_sequence = 6,
  anon_sym_DOT = 7,
  anon_sym_LBRACK = 8,
  anon_sym_RBRACK = 9,
  anon_sym_LPAREN = 10,
  anon_sym_COMMA = 11,
  anon_sym_RPAREN = 12,
  anon_sym_DASH = 13,
  anon_sym_STAR = 14,
  anon_sym_SLASH = 15,
  anon_sym_PLUS = 16,
  anon_sym_GT_EQ = 17,
  anon_sym_LT_EQ = 18,
  anon_sym_EQ = 19,
  anon_sym_LT_GT = 20,
  anon_sym_LT = 21,
  anon_sym_GT = 22,
  anon_sym_AMP = 23,
  anon_sym_PIPE = 24,
  anon_sym_SEMI = 25,
  anon_sym_of = 26,
  anon_sym_LBRACE = 27,
  anon_sym_RBRACE = 28,
  anon_sym_COLON_EQ = 29,
  sym_source_file = 30,
  sym__expr = 31,
  sym_string_literal = 32,
  sym__lvalue = 33,
  sym_record_value = 34,
  sym_array_value = 35,
  sym_function_call = 36,
  sym_unary_expression = 37,
  sym_binary_expression = 38,
  sym_sequence_expression = 39,
  sym_array_expression = 40,
  sym_record_expression = 41,
  sym_assignment_expression = 42,
  aux_sym_string_literal_repeat1 = 43,
  aux_sym_function_call_repeat1 = 44,
  aux_sym_sequence_expression_repeat1 = 45,
  aux_sym_record_expression_repeat1 = 46,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [sym_nil_literal] = "nil_literal",
  [sym_integer_literal] = "integer_literal",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_string_literal_token1] = "string_literal_token1",
  [sym_escape_sequence] = "escape_sequence",
  [anon_sym_DOT] = ".",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_LPAREN] = "(",
  [anon_sym_COMMA] = ",",
  [anon_sym_RPAREN] = ")",
  [anon_sym_DASH] = "operator",
  [anon_sym_STAR] = "operator",
  [anon_sym_SLASH] = "operator",
  [anon_sym_PLUS] = "operator",
  [anon_sym_GT_EQ] = "operator",
  [anon_sym_LT_EQ] = "operator",
  [anon_sym_EQ] = "=",
  [anon_sym_LT_GT] = "operator",
  [anon_sym_LT] = "operator",
  [anon_sym_GT] = "operator",
  [anon_sym_AMP] = "operator",
  [anon_sym_PIPE] = "operator",
  [anon_sym_SEMI] = ";",
  [anon_sym_of] = "of",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_COLON_EQ] = ":=",
  [sym_source_file] = "source_file",
  [sym__expr] = "_expr",
  [sym_string_literal] = "string_literal",
  [sym__lvalue] = "_lvalue",
  [sym_record_value] = "record_value",
  [sym_array_value] = "array_value",
  [sym_function_call] = "function_call",
  [sym_unary_expression] = "unary_expression",
  [sym_binary_expression] = "binary_expression",
  [sym_sequence_expression] = "sequence_expression",
  [sym_array_expression] = "array_expression",
  [sym_record_expression] = "record_expression",
  [sym_assignment_expression] = "assignment_expression",
  [aux_sym_string_literal_repeat1] = "string_literal_repeat1",
  [aux_sym_function_call_repeat1] = "function_call_repeat1",
  [aux_sym_sequence_expression_repeat1] = "sequence_expression_repeat1",
  [aux_sym_record_expression_repeat1] = "record_expression_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [sym_nil_literal] = sym_nil_literal,
  [sym_integer_literal] = sym_integer_literal,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_string_literal_token1] = aux_sym_string_literal_token1,
  [sym_escape_sequence] = sym_escape_sequence,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_STAR] = anon_sym_DASH,
  [anon_sym_SLASH] = anon_sym_DASH,
  [anon_sym_PLUS] = anon_sym_DASH,
  [anon_sym_GT_EQ] = anon_sym_DASH,
  [anon_sym_LT_EQ] = anon_sym_DASH,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_LT_GT] = anon_sym_DASH,
  [anon_sym_LT] = anon_sym_DASH,
  [anon_sym_GT] = anon_sym_DASH,
  [anon_sym_AMP] = anon_sym_DASH,
  [anon_sym_PIPE] = anon_sym_DASH,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_of] = anon_sym_of,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_COLON_EQ] = anon_sym_COLON_EQ,
  [sym_source_file] = sym_source_file,
  [sym__expr] = sym__expr,
  [sym_string_literal] = sym_string_literal,
  [sym__lvalue] = sym__lvalue,
  [sym_record_value] = sym_record_value,
  [sym_array_value] = sym_array_value,
  [sym_function_call] = sym_function_call,
  [sym_unary_expression] = sym_unary_expression,
  [sym_binary_expression] = sym_binary_expression,
  [sym_sequence_expression] = sym_sequence_expression,
  [sym_array_expression] = sym_array_expression,
  [sym_record_expression] = sym_record_expression,
  [sym_assignment_expression] = sym_assignment_expression,
  [aux_sym_string_literal_repeat1] = aux_sym_string_literal_repeat1,
  [aux_sym_function_call_repeat1] = aux_sym_function_call_repeat1,
  [aux_sym_sequence_expression_repeat1] = aux_sym_sequence_expression_repeat1,
  [aux_sym_record_expression_repeat1] = aux_sym_record_expression_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_nil_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_integer_literal] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_literal_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_escape_sequence] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_GT_EQ] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LT_EQ] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_GT] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_AMP] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_of] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__expr] = {
    .visible = false,
    .named = true,
  },
  [sym_string_literal] = {
    .visible = true,
    .named = true,
  },
  [sym__lvalue] = {
    .visible = false,
    .named = true,
  },
  [sym_record_value] = {
    .visible = true,
    .named = true,
  },
  [sym_array_value] = {
    .visible = true,
    .named = true,
  },
  [sym_function_call] = {
    .visible = true,
    .named = true,
  },
  [sym_unary_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_binary_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_sequence_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_array_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_record_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_assignment_expression] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_string_literal_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_function_call_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_sequence_expression_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_record_expression_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum {
  field_arguments = 1,
  field_array = 2,
  field_expression = 3,
  field_field = 4,
  field_function = 5,
  field_index = 6,
  field_init = 7,
  field_left = 8,
  field_operator = 9,
  field_record = 10,
  field_right = 11,
  field_size = 12,
  field_type = 13,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_arguments] = "arguments",
  [field_array] = "array",
  [field_expression] = "expression",
  [field_field] = "field",
  [field_function] = "function",
  [field_index] = "index",
  [field_init] = "init",
  [field_left] = "left",
  [field_operator] = "operator",
  [field_record] = "record",
  [field_right] = "right",
  [field_size] = "size",
  [field_type] = "type",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
  [2] = {.index = 2, .length = 1},
  [3] = {.index = 3, .length = 1},
  [4] = {.index = 4, .length = 3},
  [5] = {.index = 7, .length = 2},
  [6] = {.index = 9, .length = 2},
  [7] = {.index = 11, .length = 2},
  [8] = {.index = 13, .length = 2},
  [9] = {.index = 15, .length = 3},
  [10] = {.index = 18, .length = 3},
  [11] = {.index = 21, .length = 3},
  [12] = {.index = 24, .length = 5},
  [13] = {.index = 29, .length = 4},
  [14] = {.index = 33, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_expression, 1},
    {field_operator, 0},
  [2] =
    {field_function, 0},
  [3] =
    {field_type, 0},
  [4] =
    {field_left, 0},
    {field_operator, 1},
    {field_right, 2},
  [7] =
    {field_field, 2},
    {field_record, 0},
  [9] =
    {field_left, 0},
    {field_right, 2},
  [11] =
    {field_arguments, 2},
    {field_function, 0},
  [13] =
    {field_array, 0},
    {field_index, 2},
  [15] =
    {field_arguments, 2},
    {field_arguments, 3},
    {field_function, 0},
  [18] =
    {field_init, 5},
    {field_size, 2},
    {field_type, 0},
  [21] =
    {field_field, 2},
    {field_init, 4},
    {field_type, 0},
  [24] =
    {field_field, 2},
    {field_field, 5, .inherited = true},
    {field_init, 4},
    {field_init, 5, .inherited = true},
    {field_type, 0},
  [29] =
    {field_field, 0, .inherited = true},
    {field_field, 1, .inherited = true},
    {field_init, 0, .inherited = true},
    {field_init, 1, .inherited = true},
  [33] =
    {field_field, 1},
    {field_init, 3},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [4] = {
    [1] = anon_sym_DASH,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(10);
      if (lookahead == '"') ADVANCE(12);
      if (lookahead == '&') ADVANCE(33);
      if (lookahead == '(') ADVANCE(20);
      if (lookahead == ')') ADVANCE(22);
      if (lookahead == '*') ADVANCE(24);
      if (lookahead == '+') ADVANCE(26);
      if (lookahead == ',') ADVANCE(21);
      if (lookahead == '-') ADVANCE(23);
      if (lookahead == '.') ADVANCE(17);
      if (lookahead == '/') ADVANCE(25);
      if (lookahead == ':') ADVANCE(2);
      if (lookahead == ';') ADVANCE(35);
      if (lookahead == '<') ADVANCE(31);
      if (lookahead == '=') ADVANCE(29);
      if (lookahead == '>') ADVANCE(32);
      if (lookahead == '[') ADVANCE(18);
      if (lookahead == '\\') ADVANCE(6);
      if (lookahead == ']') ADVANCE(19);
      if (lookahead == '{') ADVANCE(36);
      if (lookahead == '|') ADVANCE(34);
      if (lookahead == '}') ADVANCE(37);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(9)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(11);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(15);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(12);
      if (lookahead == '\\') ADVANCE(6);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(13);
      if (lookahead != 0) ADVANCE(14);
      END_STATE();
    case 2:
      if (lookahead == '=') ADVANCE(38);
      END_STATE();
    case 3:
      if (lookahead == '}') ADVANCE(37);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(3)
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(15);
      END_STATE();
    case 4:
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(16);
      END_STATE();
    case 5:
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(4);
      END_STATE();
    case 6:
      if (lookahead == '"' ||
          lookahead == '\\' ||
          lookahead == 'a' ||
          lookahead == 'b' ||
          lookahead == 'f' ||
          lookahead == 'n' ||
          lookahead == 'r' ||
          lookahead == 't' ||
          lookahead == 'v') ADVANCE(16);
      if (lookahead == 'x') ADVANCE(8);
      if (('0' <= lookahead && lookahead <= '3')) ADVANCE(5);
      END_STATE();
    case 7:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(16);
      END_STATE();
    case 8:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(7);
      END_STATE();
    case 9:
      if (eof) ADVANCE(10);
      if (lookahead == '"') ADVANCE(12);
      if (lookahead == '&') ADVANCE(33);
      if (lookahead == '(') ADVANCE(20);
      if (lookahead == ')') ADVANCE(22);
      if (lookahead == '*') ADVANCE(24);
      if (lookahead == '+') ADVANCE(26);
      if (lookahead == ',') ADVANCE(21);
      if (lookahead == '-') ADVANCE(23);
      if (lookahead == '.') ADVANCE(17);
      if (lookahead == '/') ADVANCE(25);
      if (lookahead == ':') ADVANCE(2);
      if (lookahead == ';') ADVANCE(35);
      if (lookahead == '<') ADVANCE(31);
      if (lookahead == '=') ADVANCE(29);
      if (lookahead == '>') ADVANCE(32);
      if (lookahead == '[') ADVANCE(18);
      if (lookahead == ']') ADVANCE(19);
      if (lookahead == '{') ADVANCE(36);
      if (lookahead == '|') ADVANCE(34);
      if (lookahead == '}') ADVANCE(37);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(9)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(11);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(15);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(sym_integer_literal);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(11);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(15);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(aux_sym_string_literal_token1);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(13);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(14);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(aux_sym_string_literal_token1);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(14);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(15);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_escape_sequence);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_GT_EQ);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_LT_EQ);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_LT_GT);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '=') ADVANCE(28);
      if (lookahead == '>') ADVANCE(30);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_GT);
      if (lookahead == '=') ADVANCE(27);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_AMP);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_PIPE);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_COLON_EQ);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'n') ADVANCE(1);
      if (lookahead == 'o') ADVANCE(2);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      END_STATE();
    case 1:
      if (lookahead == 'i') ADVANCE(3);
      END_STATE();
    case 2:
      if (lookahead == 'f') ADVANCE(4);
      END_STATE();
    case 3:
      if (lookahead == 'l') ADVANCE(5);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(anon_sym_of);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(sym_nil_literal);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 1},
  [51] = {.lex_state = 1},
  [52] = {.lex_state = 1},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 3},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 3},
  [62] = {.lex_state = 3},
  [63] = {.lex_state = 3},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [sym_nil_literal] = ACTIONS(1),
    [sym_integer_literal] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [sym_escape_sequence] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_GT_EQ] = ACTIONS(1),
    [anon_sym_LT_EQ] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_LT_GT] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_AMP] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_of] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_COLON_EQ] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(60),
    [sym__expr] = STATE(48),
    [sym_string_literal] = STATE(48),
    [sym__lvalue] = STATE(3),
    [sym_record_value] = STATE(3),
    [sym_array_value] = STATE(3),
    [sym_function_call] = STATE(48),
    [sym_unary_expression] = STATE(48),
    [sym_binary_expression] = STATE(48),
    [sym_sequence_expression] = STATE(48),
    [sym_array_expression] = STATE(48),
    [sym_record_expression] = STATE(48),
    [sym_assignment_expression] = STATE(48),
    [sym_identifier] = ACTIONS(3),
    [sym_nil_literal] = ACTIONS(5),
    [sym_integer_literal] = ACTIONS(5),
    [anon_sym_DQUOTE] = ACTIONS(7),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_DASH] = ACTIONS(11),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 5,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(18), 1,
      anon_sym_LPAREN,
    ACTIONS(22), 1,
      anon_sym_LBRACE,
    ACTIONS(20), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(13), 18,
      ts_builtin_sym_end,
      anon_sym_DOT,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PLUS,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_COLON_EQ,
  [34] = 5,
    ACTIONS(26), 1,
      anon_sym_DOT,
    ACTIONS(28), 1,
      anon_sym_LBRACK,
    ACTIONS(32), 1,
      anon_sym_COLON_EQ,
    ACTIONS(30), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(24), 16,
      ts_builtin_sym_end,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PLUS,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [66] = 2,
    ACTIONS(36), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(34), 19,
      ts_builtin_sym_end,
      anon_sym_DOT,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PLUS,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_COLON_EQ,
  [92] = 2,
    ACTIONS(40), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(38), 19,
      ts_builtin_sym_end,
      anon_sym_DOT,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PLUS,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_COLON_EQ,
  [118] = 8,
    ACTIONS(3), 1,
      sym_identifier,
    ACTIONS(7), 1,
      anon_sym_DQUOTE,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_DASH,
    ACTIONS(44), 1,
      anon_sym_RPAREN,
    ACTIONS(42), 2,
      sym_nil_literal,
      sym_integer_literal,
    STATE(3), 3,
      sym__lvalue,
      sym_record_value,
      sym_array_value,
    STATE(42), 9,
      sym__expr,
      sym_string_literal,
      sym_function_call,
      sym_unary_expression,
      sym_binary_expression,
      sym_sequence_expression,
      sym_array_expression,
      sym_record_expression,
      sym_assignment_expression,
  [154] = 8,
    ACTIONS(3), 1,
      sym_identifier,
    ACTIONS(7), 1,
      anon_sym_DQUOTE,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_DASH,
    ACTIONS(48), 1,
      anon_sym_RPAREN,
    ACTIONS(46), 2,
      sym_nil_literal,
      sym_integer_literal,
    STATE(3), 3,
      sym__lvalue,
      sym_record_value,
      sym_array_value,
    STATE(41), 9,
      sym__expr,
      sym_string_literal,
      sym_function_call,
      sym_unary_expression,
      sym_binary_expression,
      sym_sequence_expression,
      sym_array_expression,
      sym_record_expression,
      sym_assignment_expression,
  [190] = 2,
    ACTIONS(52), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(50), 16,
      ts_builtin_sym_end,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PLUS,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [213] = 4,
    ACTIONS(56), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(58), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(60), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(54), 12,
      ts_builtin_sym_end,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [240] = 2,
    ACTIONS(64), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(62), 16,
      ts_builtin_sym_end,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PLUS,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [263] = 7,
    ACTIONS(3), 1,
      sym_identifier,
    ACTIONS(7), 1,
      anon_sym_DQUOTE,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_DASH,
    ACTIONS(66), 2,
      sym_nil_literal,
      sym_integer_literal,
    STATE(3), 3,
      sym__lvalue,
      sym_record_value,
      sym_array_value,
    STATE(45), 9,
      sym__expr,
      sym_string_literal,
      sym_function_call,
      sym_unary_expression,
      sym_binary_expression,
      sym_sequence_expression,
      sym_array_expression,
      sym_record_expression,
      sym_assignment_expression,
  [296] = 7,
    ACTIONS(3), 1,
      sym_identifier,
    ACTIONS(7), 1,
      anon_sym_DQUOTE,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_DASH,
    ACTIONS(68), 2,
      sym_nil_literal,
      sym_integer_literal,
    STATE(3), 3,
      sym__lvalue,
      sym_record_value,
      sym_array_value,
    STATE(49), 9,
      sym__expr,
      sym_string_literal,
      sym_function_call,
      sym_unary_expression,
      sym_binary_expression,
      sym_sequence_expression,
      sym_array_expression,
      sym_record_expression,
      sym_assignment_expression,
  [329] = 2,
    ACTIONS(72), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(70), 16,
      ts_builtin_sym_end,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PLUS,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [352] = 2,
    ACTIONS(76), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(74), 16,
      ts_builtin_sym_end,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PLUS,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [375] = 2,
    ACTIONS(80), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(78), 16,
      ts_builtin_sym_end,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PLUS,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [398] = 7,
    ACTIONS(88), 1,
      anon_sym_AMP,
    ACTIONS(90), 1,
      anon_sym_PIPE,
    ACTIONS(56), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(58), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(86), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(84), 4,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
    ACTIONS(82), 6,
      ts_builtin_sym_end,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [431] = 7,
    ACTIONS(3), 1,
      sym_identifier,
    ACTIONS(7), 1,
      anon_sym_DQUOTE,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_DASH,
    ACTIONS(92), 2,
      sym_nil_literal,
      sym_integer_literal,
    STATE(3), 3,
      sym__lvalue,
      sym_record_value,
      sym_array_value,
    STATE(35), 9,
      sym__expr,
      sym_string_literal,
      sym_function_call,
      sym_unary_expression,
      sym_binary_expression,
      sym_sequence_expression,
      sym_array_expression,
      sym_record_expression,
      sym_assignment_expression,
  [464] = 7,
    ACTIONS(3), 1,
      sym_identifier,
    ACTIONS(7), 1,
      anon_sym_DQUOTE,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_DASH,
    ACTIONS(94), 2,
      sym_nil_literal,
      sym_integer_literal,
    STATE(3), 3,
      sym__lvalue,
      sym_record_value,
      sym_array_value,
    STATE(36), 9,
      sym__expr,
      sym_string_literal,
      sym_function_call,
      sym_unary_expression,
      sym_binary_expression,
      sym_sequence_expression,
      sym_array_expression,
      sym_record_expression,
      sym_assignment_expression,
  [497] = 7,
    ACTIONS(3), 1,
      sym_identifier,
    ACTIONS(7), 1,
      anon_sym_DQUOTE,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_DASH,
    ACTIONS(96), 2,
      sym_nil_literal,
      sym_integer_literal,
    STATE(3), 3,
      sym__lvalue,
      sym_record_value,
      sym_array_value,
    STATE(9), 9,
      sym__expr,
      sym_string_literal,
      sym_function_call,
      sym_unary_expression,
      sym_binary_expression,
      sym_sequence_expression,
      sym_array_expression,
      sym_record_expression,
      sym_assignment_expression,
  [530] = 7,
    ACTIONS(3), 1,
      sym_identifier,
    ACTIONS(7), 1,
      anon_sym_DQUOTE,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_DASH,
    ACTIONS(98), 2,
      sym_nil_literal,
      sym_integer_literal,
    STATE(3), 3,
      sym__lvalue,
      sym_record_value,
      sym_array_value,
    STATE(38), 9,
      sym__expr,
      sym_string_literal,
      sym_function_call,
      sym_unary_expression,
      sym_binary_expression,
      sym_sequence_expression,
      sym_array_expression,
      sym_record_expression,
      sym_assignment_expression,
  [563] = 7,
    ACTIONS(3), 1,
      sym_identifier,
    ACTIONS(7), 1,
      anon_sym_DQUOTE,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_DASH,
    ACTIONS(100), 2,
      sym_nil_literal,
      sym_integer_literal,
    STATE(3), 3,
      sym__lvalue,
      sym_record_value,
      sym_array_value,
    STATE(39), 9,
      sym__expr,
      sym_string_literal,
      sym_function_call,
      sym_unary_expression,
      sym_binary_expression,
      sym_sequence_expression,
      sym_array_expression,
      sym_record_expression,
      sym_assignment_expression,
  [596] = 7,
    ACTIONS(88), 1,
      anon_sym_AMP,
    ACTIONS(90), 1,
      anon_sym_PIPE,
    ACTIONS(56), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(58), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(86), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(84), 4,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
    ACTIONS(102), 6,
      ts_builtin_sym_end,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [629] = 7,
    ACTIONS(3), 1,
      sym_identifier,
    ACTIONS(7), 1,
      anon_sym_DQUOTE,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_DASH,
    ACTIONS(104), 2,
      sym_nil_literal,
      sym_integer_literal,
    STATE(3), 3,
      sym__lvalue,
      sym_record_value,
      sym_array_value,
    STATE(47), 9,
      sym__expr,
      sym_string_literal,
      sym_function_call,
      sym_unary_expression,
      sym_binary_expression,
      sym_sequence_expression,
      sym_array_expression,
      sym_record_expression,
      sym_assignment_expression,
  [662] = 7,
    ACTIONS(3), 1,
      sym_identifier,
    ACTIONS(7), 1,
      anon_sym_DQUOTE,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_DASH,
    ACTIONS(106), 2,
      sym_nil_literal,
      sym_integer_literal,
    STATE(3), 3,
      sym__lvalue,
      sym_record_value,
      sym_array_value,
    STATE(40), 9,
      sym__expr,
      sym_string_literal,
      sym_function_call,
      sym_unary_expression,
      sym_binary_expression,
      sym_sequence_expression,
      sym_array_expression,
      sym_record_expression,
      sym_assignment_expression,
  [695] = 2,
    ACTIONS(110), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(108), 16,
      ts_builtin_sym_end,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PLUS,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [718] = 2,
    ACTIONS(114), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(112), 16,
      ts_builtin_sym_end,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PLUS,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [741] = 7,
    ACTIONS(3), 1,
      sym_identifier,
    ACTIONS(7), 1,
      anon_sym_DQUOTE,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_DASH,
    ACTIONS(116), 2,
      sym_nil_literal,
      sym_integer_literal,
    STATE(3), 3,
      sym__lvalue,
      sym_record_value,
      sym_array_value,
    STATE(22), 9,
      sym__expr,
      sym_string_literal,
      sym_function_call,
      sym_unary_expression,
      sym_binary_expression,
      sym_sequence_expression,
      sym_array_expression,
      sym_record_expression,
      sym_assignment_expression,
  [774] = 2,
    ACTIONS(120), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(118), 16,
      ts_builtin_sym_end,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PLUS,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [797] = 7,
    ACTIONS(3), 1,
      sym_identifier,
    ACTIONS(7), 1,
      anon_sym_DQUOTE,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_DASH,
    ACTIONS(122), 2,
      sym_nil_literal,
      sym_integer_literal,
    STATE(3), 3,
      sym__lvalue,
      sym_record_value,
      sym_array_value,
    STATE(16), 9,
      sym__expr,
      sym_string_literal,
      sym_function_call,
      sym_unary_expression,
      sym_binary_expression,
      sym_sequence_expression,
      sym_array_expression,
      sym_record_expression,
      sym_assignment_expression,
  [830] = 2,
    ACTIONS(126), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(124), 16,
      ts_builtin_sym_end,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PLUS,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [853] = 2,
    ACTIONS(130), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(128), 16,
      ts_builtin_sym_end,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PLUS,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [876] = 7,
    ACTIONS(3), 1,
      sym_identifier,
    ACTIONS(7), 1,
      anon_sym_DQUOTE,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_DASH,
    ACTIONS(132), 2,
      sym_nil_literal,
      sym_integer_literal,
    STATE(3), 3,
      sym__lvalue,
      sym_record_value,
      sym_array_value,
    STATE(43), 9,
      sym__expr,
      sym_string_literal,
      sym_function_call,
      sym_unary_expression,
      sym_binary_expression,
      sym_sequence_expression,
      sym_array_expression,
      sym_record_expression,
      sym_assignment_expression,
  [909] = 7,
    ACTIONS(3), 1,
      sym_identifier,
    ACTIONS(7), 1,
      anon_sym_DQUOTE,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_DASH,
    ACTIONS(134), 2,
      sym_nil_literal,
      sym_integer_literal,
    STATE(3), 3,
      sym__lvalue,
      sym_record_value,
      sym_array_value,
    STATE(46), 9,
      sym__expr,
      sym_string_literal,
      sym_function_call,
      sym_unary_expression,
      sym_binary_expression,
      sym_sequence_expression,
      sym_array_expression,
      sym_record_expression,
      sym_assignment_expression,
  [942] = 2,
    ACTIONS(138), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(136), 16,
      ts_builtin_sym_end,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PLUS,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [965] = 3,
    ACTIONS(58), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(60), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(54), 14,
      ts_builtin_sym_end,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [990] = 2,
    ACTIONS(60), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(54), 16,
      ts_builtin_sym_end,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PLUS,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [1013] = 7,
    ACTIONS(3), 1,
      sym_identifier,
    ACTIONS(7), 1,
      anon_sym_DQUOTE,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_DASH,
    ACTIONS(140), 2,
      sym_nil_literal,
      sym_integer_literal,
    STATE(3), 3,
      sym__lvalue,
      sym_record_value,
      sym_array_value,
    STATE(44), 9,
      sym__expr,
      sym_string_literal,
      sym_function_call,
      sym_unary_expression,
      sym_binary_expression,
      sym_sequence_expression,
      sym_array_expression,
      sym_record_expression,
      sym_assignment_expression,
  [1046] = 5,
    ACTIONS(56), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(58), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(86), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(84), 4,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
    ACTIONS(54), 8,
      ts_builtin_sym_end,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [1075] = 6,
    ACTIONS(88), 1,
      anon_sym_AMP,
    ACTIONS(56), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(58), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(86), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(84), 4,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
    ACTIONS(54), 7,
      ts_builtin_sym_end,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_PIPE,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [1106] = 2,
    ACTIONS(144), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(142), 16,
      ts_builtin_sym_end,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PLUS,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [1129] = 9,
    ACTIONS(88), 1,
      anon_sym_AMP,
    ACTIONS(90), 1,
      anon_sym_PIPE,
    ACTIONS(146), 1,
      anon_sym_COMMA,
    ACTIONS(148), 1,
      anon_sym_RPAREN,
    STATE(55), 1,
      aux_sym_function_call_repeat1,
    ACTIONS(56), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(58), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(86), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(84), 4,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
  [1163] = 9,
    ACTIONS(88), 1,
      anon_sym_AMP,
    ACTIONS(90), 1,
      anon_sym_PIPE,
    ACTIONS(150), 1,
      anon_sym_RPAREN,
    ACTIONS(152), 1,
      anon_sym_SEMI,
    STATE(54), 1,
      aux_sym_sequence_expression_repeat1,
    ACTIONS(56), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(58), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(86), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(84), 4,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
  [1197] = 9,
    ACTIONS(88), 1,
      anon_sym_AMP,
    ACTIONS(90), 1,
      anon_sym_PIPE,
    ACTIONS(154), 1,
      anon_sym_COMMA,
    ACTIONS(156), 1,
      anon_sym_RBRACE,
    STATE(56), 1,
      aux_sym_record_expression_repeat1,
    ACTIONS(56), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(58), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(86), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(84), 4,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
  [1231] = 7,
    ACTIONS(88), 1,
      anon_sym_AMP,
    ACTIONS(90), 1,
      anon_sym_PIPE,
    ACTIONS(56), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(58), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(86), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(158), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
    ACTIONS(84), 4,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
  [1260] = 7,
    ACTIONS(88), 1,
      anon_sym_AMP,
    ACTIONS(90), 1,
      anon_sym_PIPE,
    ACTIONS(56), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(58), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(86), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(160), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
    ACTIONS(84), 4,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
  [1289] = 7,
    ACTIONS(88), 1,
      anon_sym_AMP,
    ACTIONS(90), 1,
      anon_sym_PIPE,
    ACTIONS(56), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(58), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(86), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(162), 2,
      anon_sym_RPAREN,
      anon_sym_SEMI,
    ACTIONS(84), 4,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
  [1318] = 7,
    ACTIONS(88), 1,
      anon_sym_AMP,
    ACTIONS(90), 1,
      anon_sym_PIPE,
    ACTIONS(164), 1,
      anon_sym_RBRACK,
    ACTIONS(56), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(58), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(86), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(84), 4,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
  [1346] = 7,
    ACTIONS(88), 1,
      anon_sym_AMP,
    ACTIONS(90), 1,
      anon_sym_PIPE,
    ACTIONS(166), 1,
      ts_builtin_sym_end,
    ACTIONS(56), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(58), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(86), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(84), 4,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
  [1374] = 7,
    ACTIONS(88), 1,
      anon_sym_AMP,
    ACTIONS(90), 1,
      anon_sym_PIPE,
    ACTIONS(168), 1,
      anon_sym_RBRACK,
    ACTIONS(56), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(58), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(86), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(84), 4,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
  [1402] = 3,
    ACTIONS(170), 1,
      anon_sym_DQUOTE,
    STATE(51), 1,
      aux_sym_string_literal_repeat1,
    ACTIONS(172), 2,
      aux_sym_string_literal_token1,
      sym_escape_sequence,
  [1413] = 3,
    ACTIONS(174), 1,
      anon_sym_DQUOTE,
    STATE(52), 1,
      aux_sym_string_literal_repeat1,
    ACTIONS(176), 2,
      aux_sym_string_literal_token1,
      sym_escape_sequence,
  [1424] = 3,
    ACTIONS(178), 1,
      anon_sym_DQUOTE,
    STATE(52), 1,
      aux_sym_string_literal_repeat1,
    ACTIONS(180), 2,
      aux_sym_string_literal_token1,
      sym_escape_sequence,
  [1435] = 3,
    ACTIONS(158), 1,
      anon_sym_RPAREN,
    ACTIONS(183), 1,
      anon_sym_COMMA,
    STATE(53), 1,
      aux_sym_function_call_repeat1,
  [1445] = 3,
    ACTIONS(152), 1,
      anon_sym_SEMI,
    ACTIONS(186), 1,
      anon_sym_RPAREN,
    STATE(58), 1,
      aux_sym_sequence_expression_repeat1,
  [1455] = 3,
    ACTIONS(146), 1,
      anon_sym_COMMA,
    ACTIONS(188), 1,
      anon_sym_RPAREN,
    STATE(53), 1,
      aux_sym_function_call_repeat1,
  [1465] = 3,
    ACTIONS(154), 1,
      anon_sym_COMMA,
    ACTIONS(190), 1,
      anon_sym_RBRACE,
    STATE(57), 1,
      aux_sym_record_expression_repeat1,
  [1475] = 3,
    ACTIONS(192), 1,
      anon_sym_COMMA,
    ACTIONS(195), 1,
      anon_sym_RBRACE,
    STATE(57), 1,
      aux_sym_record_expression_repeat1,
  [1485] = 3,
    ACTIONS(162), 1,
      anon_sym_RPAREN,
    ACTIONS(197), 1,
      anon_sym_SEMI,
    STATE(58), 1,
      aux_sym_sequence_expression_repeat1,
  [1495] = 2,
    ACTIONS(200), 1,
      sym_identifier,
    ACTIONS(202), 1,
      anon_sym_RBRACE,
  [1502] = 1,
    ACTIONS(204), 1,
      ts_builtin_sym_end,
  [1506] = 1,
    ACTIONS(206), 1,
      sym_identifier,
  [1510] = 1,
    ACTIONS(208), 1,
      sym_identifier,
  [1514] = 1,
    ACTIONS(210), 1,
      anon_sym_of,
  [1518] = 1,
    ACTIONS(212), 1,
      anon_sym_EQ,
  [1522] = 1,
    ACTIONS(214), 1,
      anon_sym_EQ,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 34,
  [SMALL_STATE(4)] = 66,
  [SMALL_STATE(5)] = 92,
  [SMALL_STATE(6)] = 118,
  [SMALL_STATE(7)] = 154,
  [SMALL_STATE(8)] = 190,
  [SMALL_STATE(9)] = 213,
  [SMALL_STATE(10)] = 240,
  [SMALL_STATE(11)] = 263,
  [SMALL_STATE(12)] = 296,
  [SMALL_STATE(13)] = 329,
  [SMALL_STATE(14)] = 352,
  [SMALL_STATE(15)] = 375,
  [SMALL_STATE(16)] = 398,
  [SMALL_STATE(17)] = 431,
  [SMALL_STATE(18)] = 464,
  [SMALL_STATE(19)] = 497,
  [SMALL_STATE(20)] = 530,
  [SMALL_STATE(21)] = 563,
  [SMALL_STATE(22)] = 596,
  [SMALL_STATE(23)] = 629,
  [SMALL_STATE(24)] = 662,
  [SMALL_STATE(25)] = 695,
  [SMALL_STATE(26)] = 718,
  [SMALL_STATE(27)] = 741,
  [SMALL_STATE(28)] = 774,
  [SMALL_STATE(29)] = 797,
  [SMALL_STATE(30)] = 830,
  [SMALL_STATE(31)] = 853,
  [SMALL_STATE(32)] = 876,
  [SMALL_STATE(33)] = 909,
  [SMALL_STATE(34)] = 942,
  [SMALL_STATE(35)] = 965,
  [SMALL_STATE(36)] = 990,
  [SMALL_STATE(37)] = 1013,
  [SMALL_STATE(38)] = 1046,
  [SMALL_STATE(39)] = 1075,
  [SMALL_STATE(40)] = 1106,
  [SMALL_STATE(41)] = 1129,
  [SMALL_STATE(42)] = 1163,
  [SMALL_STATE(43)] = 1197,
  [SMALL_STATE(44)] = 1231,
  [SMALL_STATE(45)] = 1260,
  [SMALL_STATE(46)] = 1289,
  [SMALL_STATE(47)] = 1318,
  [SMALL_STATE(48)] = 1346,
  [SMALL_STATE(49)] = 1374,
  [SMALL_STATE(50)] = 1402,
  [SMALL_STATE(51)] = 1413,
  [SMALL_STATE(52)] = 1424,
  [SMALL_STATE(53)] = 1435,
  [SMALL_STATE(54)] = 1445,
  [SMALL_STATE(55)] = 1455,
  [SMALL_STATE(56)] = 1465,
  [SMALL_STATE(57)] = 1475,
  [SMALL_STATE(58)] = 1485,
  [SMALL_STATE(59)] = 1495,
  [SMALL_STATE(60)] = 1502,
  [SMALL_STATE(61)] = 1506,
  [SMALL_STATE(62)] = 1510,
  [SMALL_STATE(63)] = 1514,
  [SMALL_STATE(64)] = 1518,
  [SMALL_STATE(65)] = 1522,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(48),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__lvalue, 1),
  [15] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym__lvalue, 1), SHIFT(12),
  [18] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [20] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__lvalue, 1),
  [22] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [24] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expr, 1),
  [26] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [28] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [30] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__expr, 1),
  [32] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [34] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array_value, 4, .production_id = 8),
  [36] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array_value, 4, .production_id = 8),
  [38] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_record_value, 3, .production_id = 5),
  [40] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_record_value, 3, .production_id = 5),
  [42] = {.entry = {.count = 1, .reusable = false}}, SHIFT(42),
  [44] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [46] = {.entry = {.count = 1, .reusable = false}}, SHIFT(41),
  [48] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [50] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sequence_expression, 3),
  [52] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_sequence_expression, 3),
  [54] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary_expression, 3, .production_id = 4),
  [56] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [58] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [60] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binary_expression, 3, .production_id = 4),
  [62] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string_literal, 2),
  [64] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string_literal, 2),
  [66] = {.entry = {.count = 1, .reusable = false}}, SHIFT(45),
  [68] = {.entry = {.count = 1, .reusable = false}}, SHIFT(49),
  [70] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_record_expression, 7, .production_id = 12),
  [72] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_record_expression, 7, .production_id = 12),
  [74] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sequence_expression, 2),
  [76] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_sequence_expression, 2),
  [78] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_record_expression, 6, .production_id = 11),
  [80] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_record_expression, 6, .production_id = 11),
  [82] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unary_expression, 2, .production_id = 1),
  [84] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [86] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [88] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [90] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [92] = {.entry = {.count = 1, .reusable = false}}, SHIFT(35),
  [94] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [96] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [98] = {.entry = {.count = 1, .reusable = false}}, SHIFT(38),
  [100] = {.entry = {.count = 1, .reusable = false}}, SHIFT(39),
  [102] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array_expression, 6, .production_id = 10),
  [104] = {.entry = {.count = 1, .reusable = false}}, SHIFT(47),
  [106] = {.entry = {.count = 1, .reusable = false}}, SHIFT(40),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string_literal, 3),
  [110] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string_literal, 3),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call, 5, .production_id = 9),
  [114] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_call, 5, .production_id = 9),
  [116] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call, 3, .production_id = 2),
  [120] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_call, 3, .production_id = 2),
  [122] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [124] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sequence_expression, 4),
  [126] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_sequence_expression, 4),
  [128] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_record_expression, 3, .production_id = 3),
  [130] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_record_expression, 3, .production_id = 3),
  [132] = {.entry = {.count = 1, .reusable = false}}, SHIFT(43),
  [134] = {.entry = {.count = 1, .reusable = false}}, SHIFT(46),
  [136] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call, 4, .production_id = 7),
  [138] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_call, 4, .production_id = 7),
  [140] = {.entry = {.count = 1, .reusable = false}}, SHIFT(44),
  [142] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assignment_expression, 3, .production_id = 6),
  [144] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_assignment_expression, 3, .production_id = 6),
  [146] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [148] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [150] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [152] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [154] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [156] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [158] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_function_call_repeat1, 2),
  [160] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_record_expression_repeat1, 4, .production_id = 14),
  [162] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_sequence_expression_repeat1, 2),
  [164] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [166] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [168] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [170] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [172] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [174] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [176] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [178] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_literal_repeat1, 2),
  [180] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_literal_repeat1, 2), SHIFT_REPEAT(52),
  [183] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_function_call_repeat1, 2), SHIFT_REPEAT(37),
  [186] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [188] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [190] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [192] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_record_expression_repeat1, 2, .production_id = 13), SHIFT_REPEAT(62),
  [195] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_record_expression_repeat1, 2, .production_id = 13),
  [197] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_sequence_expression_repeat1, 2), SHIFT_REPEAT(33),
  [200] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [202] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [204] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [206] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [208] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [210] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [212] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [214] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_tiger(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
